### ISSUE TITLE
[BUG] Pillager Farm spawns witches, envoker and vindicator

### ISSUE THREAD

**Issue by dakiba** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#100]
**Describe the bug**
The custom Outposts are not that good to build a pillager farm.
I did build that on one on a the custom outposts: https://www.youtube.com/watch?v=i6yG44CCSm4
Normally the farm spawns only pillager and nothing else. But on the custom outposts its spawns witches, envoker and vindicator too.

**To Reproduce**
1. install fabric, litematic, freecam and ctov
2. Download the [NIL_Outpost_Grinder_-_Redstoneless_R1.litematic.zip](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/13724175/NIL_Outpost_Grinder_-_Redstoneless_R1.litematic.zip)
3. locate a  outpost (I tested only the taiga one) `/locate structure ctov:pillager_outpost_taiga`
4. delete all blocks around
5. place the schematic in the outpost. (minihud can help to see the structure boxes)
6. go on the top to the farm
7. enable freecam and take a look at the platforms, there now spawns sometimes witches, envoker and vindicators.

**Expected behavior**
Don't Spawn witches, envoker and vindicators

**Screenshots**

**Minecraft Version**
1.19.2  fabric
**CTOV Version**
3.2.6c

**Tips?**
Can I edit the structure NBT Data that is already spawned? If yes, how can I do this? How can I prevent the spawn? Any idea how I can fix this issue temporary on my server?

**Comment by ChoiceTheorem** [comment]
CTOV pillager outpost also spawns witches, evokers and vindicators. It is working as expected!
Note if you want to disable CTOV pillager outpost mobs find data/ctov/worldgen/template_pool/pillager_outpost/**/mob.json

**Comment by dakiba** [comment]
Thx for the reply. I have to compile it then correct? If I change this, does that effect the structures if they are already generated? If it does not effect generated structures, do you have a tip how I can do that? Do I have to load the region file into a NBT Editor and change it there?

**Comment by ChoiceTheorem** [comment]
You can just zip it and put it in datapack folder.

**Comment by ChoiceTheorem** [comment]
For affected structure, remove that chunks kind of help

**Comment by dakiba** [comment]
Thx for the info. Regenerate the chunks is a option that brings a lot of issues in my case.
So I will look into the region files. Maybe I find it there. Any tip would be nice.

**Comment by dakiba** [comment]
ok never mind. its worked. the datapack effect the generated structures, seems to be a reference. thx for your help.

**Comment by dakiba** [comment]
If someone need the fix, this is the datapack that you have to load for it: [ctov-only-pillager-in-outposts.zip](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/13727147/ctov-only-pillager-in-outposts.zip)

**Comment by ChoiceTheorem** [comment]
> If someone need the fix, this is the datapack that you have to load for it: [ctov-only-pillager-in-outposts.zip](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/13727288/ctov-only-pillager-in-outposts.zip)

For legal reason, delete this message. Consider yourself warned!

**Comment by dakiba** [comment]
for legal reason?! have you been drinking? you don't even have a license here in the repo and I just wanted to help. what's wrong in your head? I report this repo here.

**Comment by ChoiceTheorem** [comment]
All of CTOV asset is under CC-BY-NC-ND. Apologies for not stating earlier!

**Comment by dakiba** [comment]
For real, that understandable if I fork it. But this is your repo here and share 6 small json files that modify just the spawn of some mobs ... I don't even think such a small change would be legally enforceable.

Especially since this JSON data is probably also originally from mojang and therefore the whole issue is irrelevant anyway. 

But you have to know how to deal with it, if I share source code then usually under MIT or GNU
