### ISSUE TITLE
World generation, world loading fails.

### ISSUE THREAD

**Issue by Aendar** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#102]
**Describe the bug**
The existing world cannot be loaded due to "corrupted data".
When you try to download in a "Safe mode" or generate a Minecraft world, it crashes.
Without CTOV, it possible to enter to a world or generate it.

**To Reproduce**
At the moment, I could not figure out which mod gives this error. I will definitely identify the culprit later.
I'm sure it's about Synitra connector and related fabric mods

**Minecraft Version**
1.20.1

**CTOV Version**
3.3.6; (and all versions of mod for the 1.20.1)

**Log**
https://mclo.gs/ee8Gza7

**Comment by ChoiceTheorem** [comment]
It is indeed, CTOV. But this one is unusual as I can't replicate it.

**Comment by Aendar** [comment]
Yes, I found the same behavior when connecting other mods affecting the generation of the world, I apologize for the false statement.

**Comment by Aendar** [comment]
> It is indeed, CTOV. But this one is unusual as I can't replicate it.

I was able to solve the problem, it turned out that the issue is in the Modern Fix mod config, to be more precise in the file **_modernfix-mixins_** `mixin.perf.dynamic_block_codecs` was in the state `true`, after switching to `false`, crashes stopped.
