### ISSUE TITLE
Version not compatible with loader?

### ISSUE THREAD

**Issue by JCHB322** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#103]
**Describe the bug**
Mod ctov uses the version 3.2.6c which isn't compatible with Loader's extended semantic version format (Could not parse version number component '6c'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version

**To Reproduce**
Steps to reproduce the behaviour:
Launching the modded game

**Expected behaviour**
Modded minecraft runs

**Screenshots**

**Minecraft Version**
1.19.2

**CTOV Version**
3.2.6c

**Add-ons used**
[EMF] Entity Model Features [Fabric & Forge]
entity_model_features_fabric_1.19.2-1.1.0.jar

[ETF] Entity Texture Features - [Fabric & Forge]
entity_texture_features_fabric_1.19.2-4.6.1.jar

Additional Additions | Fabric
AdditionalAdditions-5.1.0.jar

AmbientSounds 5
AmbientSounds_FABRIC_v5.2.13_mc1.19.2.jar

Architectury API (Fabric/Forge/NeoForge)
architectury-6.5.85-fabric.jar

Areas
areas-1.19.2-5.3.jar

ARRP
arrp-0.6.4.jar

Automatic Doors
automaticdoors-1.19.2-4.6.jar

AzureLib
azurelib-fabric-1.19.2-1.0.39.jar

Balm (Fabric Edition)
balm-fabric-1.19.2-4.6.0.jar

BCLib
bclib-2.1.8.jar

Beautify: Refabricated
beautify-1.1.1+fabric-1.19.2.jar

Better Animal Models
betteranimalmodels-1.19-5.6.0-fabric.jar

Better Animals Plus
betteranimalsplus-1.19.2-11.0.10-fabric.jar

Better Animations Collection
BetterAnimationsCollection-v4.0.5-1.19.2-Fabric.jar

Better Lily Pads
betterlily-1.1.4-fabric.jar

Better Sodium Video Settings Button
bsvsb-3.0.2.jar

BetterNether
better-nether-7.1.5.jar

Biome Music[Forge/Fabric]
biomemusic-fabric-1.19.2-2.2.jar

Bits And Chisels
bitsandchisels-2.7.0.jar

Bookshelf
Bookshelf-Fabric-1.19.2-16.3.20.jar

Boosted Brightness
boosted-brightness-2.1.2+1.19.jar

Botany Pots
BotanyPots-Fabric-1.19.2-9.0.38.jar

Botany Trees
BotanyTrees-Fabric-1.19.2-5.0.12.jar

Breedable Killer Rabbit
breedablekillerrabbit-1.19.2-3.4.jar

Brewin' And Chewin' [Fabric]
brewinandchewin-fabric-2.1.5+1.19.2.jar

Bushier Flowers
bushierflowers-0.0.1-1.19.2.jar

Camp Chair
campchair-fabric.1.19-1.0.2.jar

Carpeted Stairs & Slabs
carpeted-1.19.2-1.4-fabric.jar

Charm
charm-fabric-1.19.2-4.4.4.jar

Chef's Delight [Fabric]
chefs-delight-1.0.3-fabric-1.19.2.jar

Chimes
Chimes-v2.0.1-1.19.2-Fabric.jar

Chipped
chipped-fabric-1.19.2-2.1.5.jar

ChoiceTheorem's Overhauled Village
ctov-3.2.6c.jar

Cloth Config API (Fabric/Forge/NeoForge)
cloth-config-8.3.115-fabric.jar

Collective
collective-1.19.2-7.30.jar

Comforts (Fabric 1.16.5 - 1.19.2)
comforts-fabric-6.0.7+1.19.2.jar

Connectible Chains [Fabric]
connectiblechains-2.1.4+1.19.2.jar

Continents
Continents_1.20.4_v1.1.4.jar

Convenient Decor
convenientdecor-0.2.0.jar

CorgiLib
CorgiLib-fabric-1.19.2-1.0.0.34.jar

Create Fabric
create-fabric-0.5.1-c-build.1160+mc1.19.2.jar

CreativeCore
CreativeCore_FABRIC_v2.9.4_mc1.19.2.jar

Creeper Overhaul
creeperoverhaul-2.0.9-fabric.jar

Critters and Companions
crittersandcompanions-fabric-1.19.2-2.0.2.jar

Croptopia
Croptopia-1.19.2-FABRIC-2.2.2.jar

CTM Refabricated
ctm-refabricated-1.0.1+1.19.jar

Cultural Delights [Fabric]
cultural-delights-fabric-0.14.10+1.19.2.jar

Cupboard
cupboard-fabric-1.19.2-2.1.jar

Cute Hermit Crabs (Fabric)
cutehermitcrabs-fabric-2.0.3-1.19.2.jar

Decorative Blocks
Decorative Blocks-fabric-1.19.2-3.0.0.jar

Deeper and Darker
deeperdarker-fabric-1.19.2-1.2.5.jar

Delightful Creators [Fabric] (Create and Farmer's Delight Addon)
delightful-creators-1.1.7.jar

Diagonal Fences [Forge & Fabric]
DiagonalFences-v4.2.6-1.19.2-Fabric.jar

Diagonal Windows [Forge & Fabric]
DiagonalWindows-v4.0.2-1.19.2-Fabric.jar

Ecologics
ecologics-fabric-1.19.2-2.1.11.jar

Effective
effective-1.4.jar

Enderman Overhaul
endermanoverhaul-fabric-1.19.2-0.0.0.jar

Epic Knights: Addon
[1.19.x-fabric]-Epic-Knights-Addon-1.3.jar

Epic Knights: Shields, Armor and Weapons [Fabric & Forge]
[1.19.2-fabric]-Epic-Knights-8.12.jar

Epic Knights: Slavic Armory
[1.19.x-fabric]-Epic-Knights-Slavic-Armory-1.2.jar

Exline's Awnings - Now with Corners!
exlineawnings-fabric-1.19.2-v1.1.3.jar

Extended Creative Inventory
extendedcreativeinventory-1.19.2-2.1.jar

Fabric API
fabric-api-0.77.0+1.19.2.jar

Fabric Language Kotlin
fabric-language-kotlin-1.10.17+kotlin.1.9.22.jar

Fabric Seasons
fabric-seasons-2.3+1.19.jar

Fabric Seasons: BYG Compat
fabric-seasons-byg-2.0.1.1-compat-1.0.jar

Fabric Seasons: Croptopia Compat
fabric-seasons-croptopia-2.2.2-compat-1.0.jar

Fabric Seasons: Delight Compat
fabric-seasons-delight-1.3.9-compat-1.0.jar

Fabric Seasons: Extras
fabric-seasons-extras-1.2-BETA+1.19.jar

Fabric Waystones
wraith-waystones-3.0.8+mc1.19.2.jar

Falling Leaves (Fabric)
fallingleaves-1.13.0+1.19.2.jar

Farmer's Respite (Fabric)
Farmersrespite-Fabric-2.2.5.jar

First-person Model (Forge/Fabric)
firstperson-fabric-2.2.3-mc1.19.2.jar

Floral Enchantment [Fabric]
Floral Enchantment-Fabric-1.19.2-1.1.3.jar

Forge Config API Port [Fabric]
ForgeConfigAPIPort-v4.2.11-1.19.2-Fabric.jar

Friends&Foes - Beekeeper Hut (Fabric)
friendsandfoes-beekeeperhut-fabric-mc1.19.2-1.2.0.jar

Friends&Foes - Flowery Mooblooms (Fabric)
friendsandfoes-flowerymooblooms-fabric-mc1.19.2-2.0.0.jar

Friends&Foes (Fabric) (Copper Golem, Glare, Moobloom, Iceologer, Barnacle, Wildfire, Illusioner, Rascal and Tuff Golem)
friendsandfoes-fabric-mc1.19.2-2.0.6.jar

Fusion (Connected Textures)
fusion-1.1.0c-fabric-mc1.19.2.jar

GeckoLib
geckolib-fabric-1.19-3.1.40.jar

Gravestones
gravestones-v1.13.jar

Guard Villagers (Fabric/Quilt)
guardvillagers-2.0.6-1.19.2.jar

Handcrafted
handcrafted-fabric-1.19.2-2.0.6.jar

Immersive Paintings [Fabric/Forge]
immersive_paintings-0.6.7+1.19.2-fabric.jar

Immersive Portals
immersive-portals-2.3.2-mc1.19.2-fabric.jar

Immersive structures
[Universal]Immersive Structures-2.0.7a.jar

Indium
indium-1.0.9+mc1.19.2.jar

Inventorio (Fabric)
inventorio-1.19-fabric-1.9.1.jar

Jump Over Fences
jumpoverfences-fabric-1.19.2-1.1.1.jar

Just Enough Farmer's Recipes
JustEnoughFarmersRecipes-1.19-1.0.1.jar

Just Enough Items (JEI)
jei-1.19.2-fabric-11.6.0.1018.jar

Keep My Soil Tilled
keepmysoiltilled-1.19.2-2.2.jar

Kelvin's Better Player Animations
kbpe-fabric-1.19.2-1.1-fixed.jar

Leaves Be Gone [Forge & Fabric]
LeavesBeGone-v4.0.1-1.19.2-Fabric.jar

LotTweaks
LotTweaks-mc1.19.2-fabric-2.3.4.jar

Macaw's Bridges
mcw-bridges-2.1.0-mc1.19.2fabric.jar

Macaw's Bridges - Oh The Biomes You'll Go
macawsbridgesbyg-fabric-1.19.2-1.3.jar

Macaw's Doors
mcw-doors-1.1.0fabric-mc1.19.2.jar

Macaw's Fences - Oh The Biomes You'll Go
mcwfencesbyg-fabric-1.19.2-1.1.jar

Macaw's Fences and Walls
mcw-fences-1.0.7-mc1.19.2fabric.jar

Macaw's Furniture
mcw-furniture-3.2.1-mc1.19.2fabric.jar

Macaw's Furnitures - Oh The Biomes You'll Go
mcwfurnituresbyg-fabric-1.19.2-1.1.jar

Macaw's Holidays
mcw-holidays-1.1.0-mc1.19.2fabric.jar

Macaw's Lights and Lamps
mcw-lights-1.0.6-mc1.19.2fabric.jar

Macaw's Paths and Pavings
mcw-paths-1.0.3fabric-mc1.19.2.jar

Macaw's Roofs
mcw-roofs-2.2.4b-mc1.19.2fabric.jar

Macaw's Roofs - Oh The Biomes You'll Go
z_mcwroofsbyg-fabric-1.19.2-1.2.jar

Macaw's Trapdoors
mcw-trapdoors-1.1.2-mc1.19.2fabric.jar

Macaw's Windows
mcw-windows-2.2.0-mc1.19.2fabric.jar

Magnum Torch
MagnumTorch-v4.2.3-1.19.2-Fabric.jar

Manure
manure-1.19.2-3.3.jar

Medieval Music[Forge/Fabric]
zmedievalmusic-fabric-1.19-2.0.jar

MedievalWeapons
medievalweapons-1.4.5.jar

MidnightLib
midnightlib-fabric-1.0.0.jar

Mob Scarecrows
mobscarecrow-2.2.1-1.19.1.jar

Mod Menu
modmenu-4.2.0-beta.2.jar

Moonlight Lib
moonlight-1.19.2-2.3.6-fabric.jar

Mooshroom Spawn
mooshroomspawn-1.19.2-3.5.jar

Mooshroom Tweaks
mooshroomtweaks-1.19.2-3.4.jar

More Babies (Forge & Fabric)
More Babies-fabric-1.19.1-1.0.0.jar

More Chests
morechests-2.0.0.jar

More Frogs - Fabric/Quilt/Forge
morefrogs-1.19.x-1.2.3b-fabric.jar

More Mob Variants
moremobvariants-1.0.1-1.19.2.jar

Move Boats
moveboats-1.19.2-3.2.jar

Move Minecarts
moveminecarts-1.19.2-3.4.jar

Muffin's Slime Golem
muffins-slimegolem-1.19.x-1.1.1-fabric.jar

Mythic Mobs
mythicmobs-1.19.2-fabric-1.4.5.jar

Mythic Mounts
mythic-mounts-1.19.2-7.2.jar

Name Pain
namepain-1.5.2 fabric-1.19.x.jar

Naturalist
naturalist-fabric-4.0.3-1.19.2.jar

NiftyCarts
niftycarts-2.1.0+1.19.2.jar

Night Lights
nightlights-fabric-1.19.2-1.1.jar

Not Enough Animations
notenoughanimations-fabric-1.7.0-mc1.19.2.jar

NPC Variety - Port (Fabric)
npc-variety-1.19.2-2.2.2.jar

Nyctophobia (FABRIC)
The_Graveyard_Biomes_1.6_(FABRIC)_for_1.19.2.jar

Ocean's Delight
oceansdelight-fabric-1.0.2-1.19.2.jar

Oh The Biomes You'll Go Refabricated
Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.6.jar

Overworld Piglins
overworldpiglins-1.19.2-1.4.jar

oωo (owo-lib)
owo-lib-0.8.5+1.19.jar

Patchouli (Fabric/Quilt)
Patchouli-1.19.2-77-FABRIC.jar

Placeable Blaze Rods
placeableblazerods-1.19.2-3.4.jar

Polymorph (Fabric 1.16.1 - 1.19.2)
polymorph-fabric-0.46.5+1.19.2.jar

Puzzles Lib [Forge & Fabric]
PuzzlesLib-v4.4.3-1.19.2-Fabric.jar

Random Village Names
randomvillagenames-1.19.2-3.5.jar

Realistic Bees
realisticbees-1.19.2-3.8.jar

Rechiseled
rechiseled-1.1.5b-fabric-mc1.19.2.jar

Redstone Pen
redstonepen-1.19.2-fabric-1.2.18.jar

Reese's Sodium Options
reeses_sodium_options-1.6.4+mc1.19.2-build.93.jar

Repurposed Structures (Quilt/Fabric)
repurposed_structures_fabric-6.3.28+1.19.2.jar

Resourceful Config
resourcefulconfig-fabric-1.19.2-1.0.20.jar

Resourceful Lib
resourcefullib-fabric-1.19.2-1.1.24.jar

River Redux
riverredux-0.3.0+fabric.jar

Rotten Creatures
rottencreatures-fabric-1.19.2-1.0.1.jar

Satin API
satin-1.9.0.jar

Seamless
seamless-2.2.2-fabric-1.19.2.jar

Sign Tools
signtools-fabric.1.19.2-1.0.3.jar

Simply Houses
SimplyHouses-1.1.3-1.19-fabric.jar

Skeleton Horse Spawn
skeletonhorsespawn-1.19.2-3.8.jar

Skinned Lanterns (Fabric)
skinned_lanterns-2.0.1.jar

Snow Under Trees (Fabric)​
snow-under-trees-fabric-1.0.0+1.19.2.jar

Snowy Spirit
snowyspirit-1.19.2-2.2.0-fabric.jar

Sodium
sodium-fabric-mc1.16.5-0.2.0+build.4.jar

Sodium Extra
sodium-extra-0.4.16+mc1.19.2-build.90.jar

Sound Physics Remastered
soundphysics-fabric-1.19.2-1.0.18.jar

Straw Golem Rebaled
Strawgolem-fabric-1.19.2-2.0.2-alpha.jar

SuperFancyClouds: Rearchitected
sfcr-1.7.6-mc1.19.2.jar

SuperMartijn642's Config Lib
supermartijn642configlib-1.1.8a-fabric-mc1.19.jar

SuperMartijn642's Core Lib
supermartijn642corelib-1.1.16-fabric-mc1.19.2.jar

Supplementaries
supplementaries-1.19.2-2.4.15-fabric.jar

Supplementaries Squared
suppsquared-1.19.2-1.1.2-fabric.jar

Swampier Swamps (Fabric)
swampier_swamps-1.19-1.2.1.jar

Table Top Craft (Fabric)
table_top_craft-1.19-2.1.0.jar

TerraBlender (Fabric)
TerraBlender-fabric-1.19.2-2.0.1.166.jar

The Graveyard (FABRIC)
The_Graveyard_2.3.3_(FABRIC)_for_1.19.2.jar

The Twilight Forest
twilightforest-fabric-1.19.2-4.2.357.jar

Towns and Towers
Towns-and-Towers-v.1.10.1-FABRIC-1.19.2.jar

Traveler's Titles (Fabric)
TravelersTitles-1.19.2-Fabric-3.1.0.jar

Untitled Duck Mod (Fabric)
untitledduckmod-0.6.1-1.19.2-fabric.jar

Unwrecked Ships (Fabric)
Unwrecked-Ships-0.0.3-Fabric.jar

Vanilla Degus
vanilla_degus-1.19.x-v1.3.2-fabric.jar

Villager Death Messages
villagerdeathmessages-1.19.2-3.3.jar

Villager Names (Fabric)
villagernames-1.19.2-4.5.2.jar

VillagersPlus (FABRIC)
VillagersPlus_1.9.2_(FABRIC)_for_1.19.2.jar

Visuality
visuality-0.5.6.jar

Whisperwoods
whisperwoods-1.19-2.1.1-fabric.jar

Witch Mobility [Forge & Fabric]
witchmobility-1.4.0-1.19.2-FABRIC.jar

WorldEdit
worldedit-mod-7.2.12.jar

Xaero's Minimap
Xaeros_Minimap_23.9.3_Fabric_1.19.1.jar

Xaero's World Map
XaerosWorldMap_1.37.2_Fabric_1.19.1.jar

YetAnotherConfigLib
YetAnotherConfigLib-2.2.0-for-1.19.2.jar

Your Options Shall Be Respected (YOSBR)
yosbr-0.1.2.jar

YUNG's API (Fabric)
YungsApi-1.19.2-Fabric-3.8.10.jar

YUNG's Better Desert Temples (Fabric)
YungsBetterDesertTemples-1.19.2-Fabric-2.2.2.jar

YUNG's Better Dungeons (Fabric)
YungsBetterDungeons-1.19.2-Fabric-3.2.1.jar

YUNG's Better End Island (Fabric)
YungsBetterEndIsland-1.19.2-Fabric-1.0.jar

YUNG's Better Jungle Temples (Fabric)
YungsBetterJungleTemples-1.19.2-Fabric-1.0.1.jar

YUNG's Better Mineshafts (Fabric)
YungsBetterMineshafts-1.19.2-Fabric-3.2.1.jar

YUNG's Better Nether Fortresses (Fabric)
YungsBetterNetherFortresses-1.19.2-Fabric-1.0.6.jar

YUNG's Better Ocean Monuments (Fabric)
YungsBetterOceanMonuments-1.19.2-Fabric-2.1.1.jar

YUNG's Better Strongholds (Fabric)
YungsBetterStrongholds-1.19.2-Fabric-3.2.0.jar

YUNG's Better Witch Huts (Fabric)
YungsBetterWitchHuts-1.19.2-Fabric-2.1.0.jar

YUNG's Bridges (Fabric)
YungsBridges-1.19.2-Fabric-3.1.0.jar

YUNG's Extras (Fabric)
YungsExtras-1.19.2-Fabric-3.1.0.jar

Zombie Horse Spawn
zombiehorsespawn-1.19.2-4.8.jar

Zombie Proof Doors
zombieproofdoors-1.19.2-3.2.jar

**Log**

**Additional context**

**Comment by ChoiceTheorem** [comment]
I use "6c" as rapid hotfixes thrice. Work as intended and safe to ignore.
