### ISSUE TITLE
Crash on Version 3.4.1 - Exit Code 1 [BUG]

### ISSUE THREAD

**Issue by Silverbolt666** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#105]
On a personal modpack, the mod crashes the game loading on version 3.4.1, generating the error "Exit Code 1". 

To reproduce, the following mods are used:
[modlist.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/13977359/modlist.txt)

Running Minecraft version 1.20.1; Forge version 47.2.0

CTOV Version 3.3.6 > 3.4.1

[latest.log](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/13977775/latest.log)

On version 3.3.6 works fine.

**Comment by ChoiceTheorem** [comment]
Don't use it in 1.20.1

**Comment by Silverbolt666** [comment]
Ok thanks
