### ISSUE TITLE
[BUG] Crash in the serverside 

### ISSUE THREAD

**Issue by YumatanGames** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#108]
**Describe the bug**
The game crashes when tries to generate ctov:small/village_swamp structure

**To Reproduce**
Steps to reproduce the behaviour:
Not entirely sure. I was experiencing crashes consistently at a specific place in a random world I generated. After reading the crash log I found this line:  Description: ResourceKey[minecraft:worldgen/structure / ctov:small/village_swamp]

Removing the mod fixed the issue. 

I'm using the current most recent version for Minecraft 1.20.1: Fabric 3.3.6

Another interesting thing about the crash log is this line: 

Description: Feature placement

java.lang.RuntimeException: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:deepslate_stairs' at position 0: <--[HERE]

Seems to suggest the crashes happened because the structure small/village_swamp tried to place a deepslate_stairs? 

Here is the full crashlog for you to check. I could also send you the modpack I'm building if you want, just let me know.

[crash-2024-01-19_17.01.10-server.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/13996294/crash-2024-01-19_17.01.10-server.txt)

I love your mod and appreciate your help. Thanks.

**Comment by ChoiceTheorem** [comment]
Duplicate with #91
