### ISSUE TITLE
Request: missing loottables 1.18.2

### ISSUE THREAD

**Issue by Eagletron5** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#109]
Dear ChoiceTheorem, 

I am currently working on a modpack with my friends and came across an issue. Some chests in the ctov villages are completely empty (Problem with missing loottables, no logs available for that matter). I looked through some old fixes and issues and tested the newest version of the mod in 1.19.2(ctov 3.2.6c) and the chests of the villages that were empty in 1.18.2(ctov 2.9.4) generated just fine there. 
My request beeing to please make the newest version of ctov available for 1.18.2 forge aswell, or a version where atleast the missing loottables are added. 

Big Thanks.

**MC-Version:**
1.18.2
**CTOV-Version:**
2.9.4 (newest for 1.18.2)
**modloader:**
forge 40.2.14

**Comment by ChoiceTheorem** [comment]
Not supporting CTOV 1.18.2 right now! Likely won't fix it!
