### ISSUE TITLE
[1.19] [Forge] [Worker-Main5/WARN] [minecraft/JigsawPlacement]: Empty or non-existent pool

### ISSUE THREAD

**Issue by Nockl** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#11]
Using Structure Compass cause log spam making server unresponsive
![Screenshot 2023-01-10 at 00-44-29 Forge 1 19 2 Client Log #yrBeG88](https://user-images.githubusercontent.com/65879304/211457302-f1394c01-0576-4fbe-82e6-3607aaa31492.png)

**Comment by ChoiceTheorem** [comment]
The log spam comes from not installing waystone add-on I'll fix it in the next version.

**Comment by ChoiceTheorem** [comment]
Fixed in 3.1.5
