### ISSUE TITLE
[BUG] "UPDATE" link is "https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village" = "v.3.3.1+1.20.x/OUTDATED"

### ISSUE THREAD

**Issue by markygnlg** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#110]
**Describe the bug**

1.) I loaded/started mc1.20.1;
2.) mods button showed an update was available for this mod;
3.) I clicked on the link within the mc 'mods' button;
4 ) it sent me to the github (outdated = 3.3.1) link;
5. I googled this mod && found the proper link at curseforge = 3.4.2_04Feb2024)
{{ (5b.) why have you not moved to mod-rinth? }}

**To Reproduce**
Steps to reproduce the behaviour:

[AS ABOVE]

**Expected behaviour**

1. A DIRECT link to the updated file (on modrinth);

**Screenshots**

**Minecraft Version**

1.20.1

**CTOV Version**

ctov-3.3.6

**Comment by markygnlg** [comment]
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/issues" #optional

# A URL to query for updates for this mod. See the JSON update specification <here>
updateJSONURL = "https://api.modrinth.com/updates/fgmhI8kH/forge_updates.json" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village" #optional

**Comment by markygnlg** [comment]
WTF?

**Comment by ChoiceTheorem** [comment]
- Using a "#" in markdown will cause the text to be marked as headers.
- In your scenarios, it's better to paste the code in the code box.
- Issue acknowledged, will change the link to Modrinth in the next update.

**Comment by markygnlg** [comment]
`is this a code box?`
hash = 'headers
`or is this a cose box`
 ... same quote marks so ... not wqhat I was expecting - not a prob tho... All's answered.
