### ISSUE TITLE
[BUG] FPS DEAD 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#111]
1.19.2 Forge 43.3.5
Ctov-3.2.6c.jar
Insanity Shader

Wild drawdown of FPS and TPS
Mmm, it has something to do with Shaders. Since when they are disabled, FPS does not drop so much. But at the same time it concerns the village. 

![2024-02-07_17 44 23](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/106809386/35420587-9178-4d04-8133-ee68a35c836b)

**Comment by ChoiceTheorem** [comment]
The lags looks like a client end lag. Not something related to CTOV.
