### ISSUE TITLE
[BUG] Underground villages do not generate

### ISSUE THREAD

**Issue by dhouck** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#113]
**Describe the bug**
Underground villages do not generate in version 3.4.2, and if placed manually do not have houses, only job sites.

The generation might be deliberately disabled because of the house issue, but if so I haven’t found documentation about it.  This is why I’m submitting one issue instead of splitting it up.

I don’t know why the houses don’t generate but the villages don’t generate because their structure set file has a `.txt`extension instead of `.json`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use `/locate` to try to find an underground village
2. Observe that the game fails to find it in a reasonable distance
3. Use `/place` to make an underground village
4. Try to find a villager house or villagers in the newly placed village

**Expected behaviour**
For step two: a village is located

For step four: there are villagers and beds for them to sleep in

**Screenshots**

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.2

**Add-ons used**
Comparibility mods for Create: Structures, Farmer’s Delight, Chef’s Delight

**Log**
None

**Additional context**
None

**Comment by ChoiceTheorem** [comment]
Disabled for technical reasons
