### ISSUE TITLE
[BUG] Incompatible With Farmers Delight Refabricated

### ISSUE THREAD

**Issue by PolyframeX** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#118]
**Describe the bug**
Farmer's Delight Refabricated Is The New Port Of Farmer's Delight. However this mod does not support it, and when loading into a world. The CTOV datapack will fail and proceed as normal, without farmer delight content

**To Reproduce**
Steps to reproduce the behaviour:
1. Download both CTOV and farmers delight refabricated
2. Load a world
3. See bug

**Expected behaviour**
Content should load as normal

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.2

**Add-ons used**
Create: Structures
Friends and Foes
Paladins & Priests
Wizards

**Log**
Unavailable

**Comment by Allexio** [comment]
Please do not break the original port's compatibility just to be compatible with MehVahdJukaar's version.

**Comment by ChoiceTheorem** [comment]
Did you install Lithostitched?

**Comment by PolyframeX** [comment]
Yes, I had lithostitched installed.

**Comment by ChoiceTheorem** [comment]
Hmm, I checked it's compatible. My compat is activated just after seeing a mod with id "farmersdelight" in the list.
