### ISSUE TITLE
Desert Village Crash

### ISSUE THREAD

**Issue by SkyArrow76** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#12]
Noticed this happening with Badlands villages. Wasn't sure which mod was causing this, but by process of elimination (through removing one at a time), it seems to be this one. Here's the full crash report.
[crash-2023-01-24_20.20.04-server.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/10495297/crash-2023-01-24_20.20.04-server.txt)
Seems to be something relating to this line 
"com.mojang.brigadier.exceptions.CommandSyntaxException: Block minecraft:smooth_sandstone_stairs does not have property 'facin' at position 34: ...ne_stairs[<--[HERE]"

Using version [Universal]CTOV-v3.1.4 in Fabric.

**Comment by ChoiceTheorem** [comment]
I need your mod list please.

**Comment by SkyArrow76** [comment]
[modlist 1.19.3 fabric.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/10502405/modlist.1.19.3.fabric.txt)
Here you go
