### ISSUE TITLE
[BUG] Incorrect structure appears from All Bark All Bite [AOF7]

### ISSUE THREAD

**Issue by nitrofenix** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#120]
**Describe the bug**
The loot tables of a barrel inside a `ctov:pillager_outpost_snowy` structure is incorrect -- it's using a loot table for the "All Bark All Bite" mod, despite it not being part of this modpack:
![2024-04-02_19 08 33](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/50662839/1302b202-b191-4e36-8ad6-6959e494958d)

**To Reproduce**
Steps to reproduce the behaviour:
1. `/locate structure ctov:pillager_outpost_snowy` (seed used for screenshots in this post: `1616198435427200770`)
2. Look for a kennel/cage structure:
![2024-04-02_19 10 07](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/50662839/ae0571fb-4292-4cf1-9248-428e244ecd58)
3. Open the chest and see the following error:
![image](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/50662839/465826be-a9c2-45b8-b6d7-672146439594)

**Expected behaviour**
Loot table should probably be `minecraft:chests/pillager_outpost` or some CTOV equivalent

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.2

**Add-ons used**
All mods included with AOF7 v2.0.2

**Comment by ChoiceTheorem** [comment]
This kennel structure doesn't suppose to be here in the first place!

**Comment by ChoiceTheorem** [comment]
Fixed in CTOV 3.4.3
