### ISSUE TITLE
[BUG] CTOV villages and Vanilla villages can overlap

### ISSUE THREAD

**Issue by Hati-** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#121]
**Describe the bug**
The villages from CTOV can overlap with Vanilla villages.

**To Reproduce**
Install CTOV and look look around for overlapping villages.

Alternatively go to https://map.jacobsjo.eu/ and upload the modpack and show structure positions, then look for villages being very close to eachother.
I've made a basic datapack that easily shows the spawns of both CTOV and Vanilla villages for use on that website: [CTOV_vs_Vanilla_Villages.zip](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/14836589/CTOV_vs_Vanilla_Villages.zip)

Emeralds are Vanilla villages and Apples are CTOV villages:
![image](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/10211721/d25e01c1-24d2-47bf-ae14-62a0742baf71)

**Expected behaviour**
Villages are villages and they shouldn't be too close or overlap each-other just like in vanilla Minecraft. CTOV Villages should be spaced away from vanilla villages.

**Screenshots**
Using the MiniHUD mod to show structure bounding boxes. Green boxes are Vanilla villages and red boxes are CTOV villages.

Seed: 8122880761972265217 | Position: 88 130 91
![2024-04-02_12 56 02](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/10211721/b3b6231f-079a-488f-85cd-a665e94134b0)

Seed: 8122880761972265217 | Position: -2857 100 -2012
![2024-04-02_12 57 10](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/10211721/f31ed1ef-34cc-4c95-9a13-02aa922987a5)

Seed: 8122880761972265217 | Position: 1637 96 2506
![2024-04-02_12 58 56](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/10211721/45e67cd0-fe71-4a55-9daa-fbb900f1e575)

And this is the worst possible scenario; The CTOV village is spawning on the exact same chunk as a Vanilla village!
Seed: 1668420055860896102 | Position: -3822 153 373
![2024-04-02_14 08 30](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/10211721/78ef30cb-da63-4b80-8e06-f2f4d2a29356)

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.2

**Add-ons used**
Mod Loader: Quilt Loader 0.24.0
- qfapi-7.5.0_qsl-6.1.2_fapi-0.91.0_mc-1.20.1.jar
- minihud-fabric-1.20.1-0.27.0.jar
- malilib-fabric-1.20.1-0.16.3.jar
- BBOutlineReloaded-2.6-1.20.1-fabric.jar
- wits-1.1.0+1.20.1-fabric.jar
- ctov-3.4.2.jar

**Log**
N / A

**Additional context**
This issue stems from you separating the CTOV's village structure_set away from Vanilla's village structure_set in commit https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/commit/6af4fabee049e23122c47bcd1c1d19e0bf5fbe37 . This will cause the two different kind of villages to generate independently from each-other with no spacing between. 
This commit was also the cause for issue #112, because you didn't change the placement parameters in `structure_set/pillager_outposts.json`, but even if you did there would still be a chance for the outposts to be too close or overlap.

I personally think you should put the village and outposts back into Vanilla's structure_set.

**Comment by Hati-** [comment]
I noticed you're reconstructing the mod from being a simply datapack into being a mod with mixins code. Maybe look at https://github.com/MaxenceDC/sparsestructures on how they're modifying structure_set and use that to programmatically add the CTOV structures into `minecraft/worldgen/structure_set/villages.json`? That way this mod would be compatible with mods/datapacks that also adds villages through minecraft's structure_set.

**Comment by Hati-** [comment]
I see you're using the lithostitched library to add Croptopia compatibility.
Maybe use that library to add the new CTOV structures to `minecraft/worldgen/structure_set/villages.json` and `minecraft/worldgen/structure_set/pillager_outposts.json`?
https://github.com/Apollounknowndev/lithostitched/wiki/Worldgen-Modifiers#add_structure_set_entries

**Comment by ChoiceTheorem** [comment]
Fixed for CTOV 3.4.5
