### ISSUE TITLE
[BUG] Another mod's loot table referenced in structure

### ISSUE THREAD

**Issue by Linguardium** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#127]
**Describe the bug**
Loot table referenced in structure that does not exist: https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/blob/1.20/common/src/main/resources/data/ctov/structures/pillager_outpost/badlands/feature_kennel.nbt

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to structure above
2. Click on barrel

**Expected behaviour**
loot generates

**Screenshots**
N/A

**Minecraft Version**
N/A

**CTOV Version**
Version linked above from your github

**Add-ons used (Before 1.20)**
N/A

**Do you install Lithostitched?(1.20+)**
N/A

**Log**
N/A

**Additional context**
Linked your own structure nbt above from your github

**Comment by ChoiceTheorem** [comment]
Because it's a structure that spawn in presence of All Bark All Bite mod

**Comment by Linguardium** [comment]
ah, didnt realize it was fixed in 909efc2570816d0582cb7b25b1df1daff34f0b20
Sorry for the trouble
