### ISSUE TITLE
[BUG] fortified taiga chests reference non-existant loot table (recurs in addons that add copies of the structure)

### ISSUE THREAD

**Issue by Linguardium** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#128]
**Describe the bug**
https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/blob/1.21-reworked/src/main/ctov-croptopia-add-on/data/ctov/structures/village/taiga_fortified/jobsite/orchard.nbt

         [ 2, 1, 3 ] [ minecraft:chest ]: ctov:village/taiga/farm

         [ 2, 1, 4 ] [ minecraft:chest ]: ctov:village/taiga/farm

**To Reproduce**
Steps to reproduce the behaviour:
open nbt
view chest loot table
fail to find loot table in datapack provided

**Expected behaviour**
loot table should exist

**Screenshots**
N/A

**Minecraft Version**
N/A
**CTOV Version**
N/A
**Add-ons used (Before 1.20)**
See above, linked to your github 

**Do you install Lithostitched?(1.20+)**
N/A

**Log**
N/A

**Additional context**
Linked the nbt directly on the github, see above

**Comment by ChoiceTheorem** [comment]
1.20 is the main branch of development.

**Comment by Linguardium** [comment]
thats fine, I dont see the addons in that branch otherwise i would have linked it.  The addon https://modrinth.com/datapack/ctov-croptopia-compat/version/2.0+mod links back to this issue tracker. if there is a better place to report it, let me know and i will re-open there
