### ISSUE TITLE
[BUG] Crash while generating savanna vilage

### ISSUE THREAD

**Issue by JedaiGames** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#129]
Game tries to generate garbage pile from rats mod, while said mod wasn't installed
Playing on Minecraft Forge 1.20.1

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Minecraft 1.20.1 with Forge 47.2.21
2. Generate new world.
3. Find a village
4. See the crash and error

**Expected behaviour**
All will work as intended.

Minecraft 1.20.1 Forge

CTOV 3.4.2

**Do you install Lithostitched?(1.20+)**
Yes

**Log**
[crash-2024-04-14_19.35.30-server.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/14971418/crash-2024-04-14_19.35.30-server.txt)

**Comment by ChoiceTheorem** [comment]
Update to 3.4.3!
