### ISSUE TITLE
May compat with Better Village & The Missing Villages? 

### ISSUE THREAD

**Issue by kressety** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#13]
Can you make it compatible with [Better Village](https://www.curseforge.com/minecraft/mc-mods/better-village-fabric) and [The Missing Villages](https://www.curseforge.com/minecraft/mc-mods/the-missing-villages) ?

**Comment by ChoiceTheorem** [comment]
As it is, the mod is compatible with both mods.

**Comment by kressety** [comment]
Got it. Thank you.
