### ISSUE TITLE
[Refinement] Waystones rarely generate in Forge 1.20.1

### ISSUE THREAD

**Issue by BMedinaASC** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#132]
**Describe the bug**
Waystones rarely generate in CTOV villages, even with "forceSpawnInVillages" set to true in Waystones Config. Also, CTOV seems to greatly increase the village spawn frequency.

**To Reproduce**
Steps to reproduce the behaviour:
1. Download CTOV, Lithostitched, and Waystones
2. Set "forceSpawnInVillages" in Waystones config to true
3. Generate a world and locate villages (which spawn much more frequently than vanilla)
4. Most CTOV villages will not contain a waystone (11/13 vanilla villages did have a waystone, only 2/10 CTOV villages had a waystone)

**Expected behaviour**
Waystones will spawn in most CTOV villages in this configuration. Vanilla village frequency preserved.

**Minecraft Version**
1.20.1 (Forge 47.2.30)

**CTOV Version**
3.4.3

**Add-ons used (Before 1.20)**
N/A

**Do you install Lithostitched?(1.20+)**
Yes

**Comment by ChoiceTheorem** [comment]
Fixed in CTOV 3.4.5
