### ISSUE TITLE
[BUG] about a billion pillagers

### ISSUE THREAD

**Issue by kerrschtein** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#133]
**Describe the bug**
In certain CTOV Pillager Outposts, villagers seem to infinitely spawn and won't stop, no matter how many I kill. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a CTOV Pillager Outpost

**Expected behaviour**
Less pillagers?

**Screenshots**
![image](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/55864549/0168a320-e6de-4cce-a579-95db430d03a1)

**Minecraft Version**
1.20.1
**CTOV Version**
3.4.3
**Add-ons used (Before 1.20)**

**Do you install Lithostitched?(1.20+)**
Yes
**Log**

**Additional context**
There's around a hundred right now...

**Comment by ChoiceTheorem** [comment]
Fixed in 3.4.4
