### ISSUE TITLE
[BUG] Double villages when used with latest Terralith

### ISSUE THREAD

**Issue by Trinketina** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#134]
When using CTOV with [Terralith](https://modrinth.com/mod/terralith) it currently generates villages right next to vanilla ones instead of overhauling them.
![2024-05-14_21 02 35](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/143371814/3d3a5997-e8c4-463b-a48f-465e63d909fb)
![2024-05-14_21 03 37](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/143371814/b73ca443-cc31-41c7-a75b-b78a969ebf88)

**Steps to reproduce the behaviour:**
1. Install CTOV and Terralith together.
2. this exact seed for testing is: 3933110227841336211
3. first screenshot is at spawn
4. second is at x172 / y150 / z-430

Minecraft v. **1.20.1**

CTOV v. **3.4.3** (latest as of typing this)

Terralith v. **2.5.0**

**Do you install Lithostitched?(1.20+)**
Yes & No | it happens with both Lithostitched installed and not

**Comment by ChoiceTheorem** [comment]
Overhauled village is a bit misleading now that it only adds no change villages.
