### ISSUE TITLE
Iron's Spellbooks priest mob not spawning in priest house

### ISSUE THREAD

**Issue by johalun** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#136]
Describe the bug
Iron's Spells and Spellbooks priest house generates but the priest is nowhere to be seen.

To Reproduce
Install CTOV and Iron's Spells and Spellbooks
Visit a CTOV village

Expected behaviour
There should be an Iron's Spells and Spellbooks priest in the priests house, or in the village.

Minecraft Version
1.20.1

CTOV Version
ctov-forge-3.4.3

Add-ons used (Before 1.20)

Do you install Lithostitched?(1.20+)
Yes

**Comment by ChoiceTheorem** [comment]
Fixed in CTOV 3.4.4
