### ISSUE TITLE
[FEATURE REQUEST] Cap gazebo spawn rate per village 

### ISSUE THREAD

**Issue by muon-rw** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#138]
**Describe the bug**
More or less described in #101 
Integration for Gazebos will often spawn the structure upwards of 3 times, which feels very out of place. 

**Minecraft Version**
Minecraft 1.20.1

**CTOV Version**
ctov-fabric-3.4.3

**Do you install Lithostitched?(1.20+)**
Yes

**Additional context**
Forgive my potential ignorance on worldgen mechanics here, and sorry if the duplicate issue is annoying, but #101 was closed because you said it wasn't something you could control. 

However, now that the mod uses Lithostitched, if you switched your villages' structure types to `lithostitched:jigsaw`, could you move these weighted `single_pool_element`s in your template pool additions into a `limited` or `guaranteed`? 

https://github.com/Apollounknowndev/lithostitched/wiki/Structure-Utilities#limited

**Comment by ChoiceTheorem** [comment]
Fixedin upcoming CTOV 3.4.4
