### ISSUE TITLE
More Villagers Missing Professions

### ISSUE THREAD

**Issue by jrkulmer** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#14]
Hi there,

Is it a conscious choice to leave out the following professions, or is it simply a case of you've not gotten round to implementing them yet? Just curious!

- netherologist
- enderologist
- florist
- miner 
- forester

Cheers 
James

**Comment by ChoiceTheorem** [comment]
It is a deliberate decision not to include netherologist, miner and enderologist. The other two are implemented.
