### ISSUE TITLE
Which mod generated this structure

### ISSUE THREAD

**Issue by zc1108aaa** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#142]
![2024-06-08_20 10 00](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/155424398/138fc2d9-9a3b-4196-86a4-e9b87112c72e)
1
![2024-06-08_20 12 00](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/155424398/1c9f062d-24d3-4c94-bfc8-d78903faf78a)

**Comment by ChoiceTheorem** [comment]
Not CTOV!
