### ISSUE TITLE
[BUG] All buildings in village_jungle_tree are set into the ground by one block

### ISSUE THREAD

**Issue by Robynstar** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#147]
**Describe the bug**
In all three sizes of the "village_jungle_tree" type of village, all the buildings are one block lower than the rest of the ground. Either their ground-level is off by one, or trying to set the base of the stilts into the ground has gone awry slightly.

**To Reproduce**
Locate any village_jungle_tree village and look at the ground under all the buildings

**Expected behaviour**
Buildings not to all have square 1-block deep pits under them.

**Screenshots**
![2024-06-09_20 57 53](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/2327643/3213d62b-c13d-44ba-8c62-9f578a4c5adb)

**Minecraft Version**
1.20.1

**CTOV Version**
ctov-forge-3.4.3.jar

**Do you install Lithostitched?(1.20+)**
Yes

**Comment by Robynstar** [comment]
![Uploading 2024-06-09_21.08.46.png…]()

Double-checked with absolutely no mods except CTOV and Lithostitched.

**Comment by ChoiceTheorem** [comment]
It's a issue that I'm awared of but not fixed yet

**Comment by ChoiceTheorem** [comment]
Will be fixed in the next version of CTOV for 1.20 and 1.21.
