### ISSUE TITLE
[BUG] Wizards Compat 2.1 not installable in 1.20.1 modpacks via Modrinth

### ISSUE THREAD

**Issue by Routhinator** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#153]
**Describe the bug**
For some reason, the 2.1 version of Wizards Compat is not installable on 1.20.1 modpacks according the the Modrinth API - the latest release seems to be 2.0a which has the bug with `minecraft:deepslate_stairs` 

I am experiencing this issue trying to install using the "Add mods" feature of ATLauncher. Looking at the version release on Modrinth I'm not certain why this is occuring https://modrinth.com/datapack/ctov-wizards-compat/version/2.1 - but it lead me to believe the release was not available until I caught mention of it in other issues.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open any 1.20.1 pack in ATLauncher or any launcher with Modrinth API support
2. Click Add Mods
3. Search for Wizards Compat and click the dropdown for available versions, only 2.0 and 2.0a will appear.

**Expected behaviour**
2.1 should be available in the API

**Screenshots**

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.3

**Add-ons used (Before 1.20)**
Wizards Compat

**Do you install Lithostitched?(1.20+)**
Yes

Logs don't really apply as this is about the availability of the release on Modrinth.

**Comment by Routhinator** [comment]
Oh wait - I just realized why - it's been uploaded as a zip rather than a jar file

**Comment by ChoiceTheorem** [comment]
And you didn’t read that CTOV on 1.20.x no longer used addons

**Comment by Routhinator** [comment]
Also oddly compared to other releases, filename is `ctov-wizards-add-on-v2.1.zip` - instead of `ctov-wizards-compat-v2.1.jar`

**Comment by Routhinator** [comment]
> And you didn’t read that CTOV on 1.20.x no longer used addons 

Yes I apparently missed that - but are you saying the compats are no longer necessary?

**Comment by Routhinator** [comment]
> And you didn’t read that CTOV on 1.20.x no longer used addons

Can you point me to where I missed this? I just checked your changelog, FAQ, and mod compatibility sections on Curse and Modrinth, as well as the README in this repo, and I'm not seeing where I missed any explicit mention of compat packs no longer being needed.

**Comment by Routhinator** [comment]
I'm confused about your comment and beginning to wonder if "Add Ons" are something different to "Compat" datapacks. I'm brand new to this mod and only started playing with it a few weeks ago, have only used it on 1.20.1 - so I've missed something.

The docs still lead me to strongly expect that compat datapacks are required, and your comments helping others on Curse state that all compat's will be for 1.20.x going forward make me wonder what "add ons" are in this context?

**Comment by Routhinator** [comment]
Wait, ok - I am guessing this changelog line is what I missed:

[[Fabric]CTOV-v.3.4.1](https://modrinth.com/mod/ct-overhaul-village/version/3.4.1)
by [ChoiceTheorem](https://modrinth.com/user/ChoiceTheorem) on Jan 15, 2024
Download

    Make most compatibility built-in except croptopia.

I'll rip all the compats out then and see how a fresh worldgen looks.

**Comment by Routhinator** [comment]
Yeah ok, seems like I really don't need the compats anymore. 

A suggestion, make this clearer in the Mod Support section of the readme/descriptions.
