### ISSUE TITLE
[BUG] Waystones generated by CTOV dont listen to unbreakable config

### ISSUE THREAD

**Issue by TobiasL-05** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#154]
If you set the unbreakable config to true with Waystones the waystones generated in CTOV villages will still be breakable

Steps to reproduce the behaviour:
1. download CTOV and Waystones 
2. set the "generatedWaystonesUnbreakable" config in waystones to "true"
3. generate a world
4. still be able to mine the waystones if generated in a CTOV village.

**Expected behaviour**
Expected behaviour is that you wont be able to mine the waystones at all, not just the ones generated outside a village.

**Versions**
MC 1.20.1
Forge 47.2.30
CTOV 3.4.4 (and below)

**Do you install Lithostitched?(1.20+)**
Yes

**Comment by ChoiceTheorem** [comment]
Please put this issue to waystone side, likely has to be fixed from that end.

**Comment by TobiasL-05** [comment]
I will also put it there but the waystones generated outside the villages 1. have a pre-generated name and 2. listen tot the config, so I thought it belonged here

**Comment by TobiasL-05** [comment]
![image](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/133211262/041ed59b-6e87-43a4-b838-e641140c196a)

this is the response from Waystones

**Comment by ChoiceTheorem** [comment]
From [this](https://github.com/TwelveIterationMods/Waystones/issues/684), this issue kind of no longer matters in the near future so, closing this issue.
