### ISSUE TITLE
[CRASH] Recent CTOV Update in 1.20.4 Fabric

### ISSUE THREAD

**Issue by GamebP** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#155]
**Describe the bug**
Making a new world

**To Reproduce**
Steps to reproduce the behaviour:
1. Download Fabric 0.15.11
2. Have FabricAPI 0.97.1+1.20.4.jar
3. Then download [ctov-3.4.4.jar](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village/files/5423749)
4. Open game
5. Try to create a world

**Expected behaviour**
On create world it should crash and put you in Minecraft Launcher

**Screenshots**
![image](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/88152063/9bce9843-ffac-4dfc-b068-a05a7a299d2b)

**Minecraft Version**
1.20.4 Fabric

**CTOV Version**
ctov-3.4.4.jar

**Add-ons used (Before 1.20)**
?

**Do you install Lithostitched?(1.20+)**
No

**Additional context**
ctov-fabric-3.4.3.jar runs without issues but the new updated one runs with issues

**Log files**
[crash-client.txt](https://github.com/user-attachments/files/15828869/crash-2024-06-14_00.12.18-client.txt)
[latest.log](https://github.com/user-attachments/files/15828872/latest.log)

**Comment by ChoiceTheorem** [comment]
Install lithostitched should fix your problem!

**Comment by GamebP** [comment]
Adding Lithostitched fixed it. Make it require the mod eather reports might come in.
