### ISSUE TITLE
[BUG] CTOV can't create single player game

### ISSUE THREAD

**Issue by willis1030** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#158]
MC 1.20.1
Forge 47.3.1
CTOV 3.4.4

**Comment by ChoiceTheorem** [comment]
Did you installed lithostitched?

**Comment by willis1030** [comment]
No, I don't install lithostitched. So...I install it now and CTOV works!
Sorry for my mistake.

**Comment by Poopooracoocoo** [comment]
@ChoiceTheorem Please add the Lithostitched dependency to your Forge `mods.toml` and to your Fabric `fabric.mod.json`
