### ISSUE TITLE
[BUG] Lithostitched dependency is not declared in mods.toml or fabric.mods.json

### ISSUE THREAD

**Issue by Poopooracoocoo** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#161]
**Describe the bug**
Your Forge `mods.toml` and your Fabric `fabric.mod.json` should have the dependency on lithostitched to prevent crashes when it is missing and prompt the user to install it.

In particular this helps manual download users who may not check dependencies. Yes, it's their fault but this can help!

**To Reproduce**
Steps to reproduce the behaviour:
1. Launch game with CTOV but without Lithostitched

**Expected behaviour**
Prompt users to install Lithostitched without crashing

**Screenshots**

**Minecraft Version**
1.20.1
**CTOV Version**
3.4.4
**Add-ons used (Before 1.20)**

**Do you install Lithostitched?(1.20+)**
No
**Log**

**Additional context**

**Comment by ChoiceTheorem** [comment]
Completed in [this commit](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/commit/ca5b1b999d6c1a1ee1b7627f509a835e932af2ad)
