### ISSUE TITLE
[BUG] village_swamp_fortified has no structure type

### ISSUE THREAD

**Issue by Aismaelinc** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#168]
**Describe the bug**
World generation Stops with the following lines

[07/07/2024 10:08:37 AM] [Server thread/ERROR] Cowardly refusing to save structure ctov:small/village_swamp_fortified as it has no structure type! Report this to the structure mod author!
[07/07/2024 10:08:43 AM] [Worker-Main-15/ERROR] Hanging entity at invalid position: class_2338{x=203, y=48, z=159}

**To Reproduce**
let an World generate with an village_swamp_fortified 

**Expected behaviour**
no error and Freeze

**Screenshots**

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.4 fabric

**Add-ons used (Before 1.20)**

**Do you install Lithostitched?(1.20+)**
Yes/No(You install it first)

yes

**Log**

[07/07/2024 10:08:37 AM] [Server thread/ERROR] Cowardly refusing to save structure ctov:small/village_swamp_fortified as it has no structure type! Report this to the structure mod author!
[07/07/2024 10:08:43 AM] [Worker-Main-15/ERROR] Hanging entity at invalid position: class_2338{x=203, y=48, z=159}

**Comment by ChoiceTheorem** [comment]
I'd like some more infos
1. Is this updating CTOV on an existing world?
2. What version of lithostitched did you use?

**Comment by Aismaelinc** [comment]
**1. Is this updating CTOV on an existing world?**
- Could you please specify the question?
- I will try to answer based on my understanding:
  I entered a new area in my world, and the chunk loader stopped. Minecraft froze when placing blocks, and this error appeared in the logs.

**2. What version of lithostitched did you use?**
- I used the version `lithostitched-fabric-1.20.1-1.1.6.jar`.

Do you need any further information?



I hope this helps! If you need any more adjustments, please let me know.

**Comment by ChoiceTheorem** [comment]
1. Rephrase, A new area in the old world right? Have you use previous version of CTOV before on that world?

**Comment by Aismaelinc** [comment]
Yes, i had used 3.4 beta before

**Comment by ChoiceTheorem** [comment]
Hmm, I'll have to come up with a fix later

**Comment by ChoiceTheorem** [comment]
It must have been some breaking changes I accidentally introduced in CTOV 3.4.x

**Comment by ChoiceTheorem** [comment]
So, is the error fixed? If so, close the issue.

**Comment by Aismaelinc** [comment]
Yes it is fixed, Thx
