### ISSUE TITLE
[CRASH] Med swamp fortified generation crashes game

### ISSUE THREAD

**Issue by ECrites** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#171]
**Describe the bug**
 fortified swamp villages crashes game from unknown block type 'minecraft:deepslate_stairs'

**To Reproduce**
Steps to reproduce the behaviour:
1. have fortified swamp villages generate in world

**Expected behavior**
Issue has been seen before in earlier versions, but was thought to be patched on June 8, 2024.

**Minecraft Version**
1.20.1
**CTOV Version**
v3.4.5
**Add-ons used (Before 1.20)**

**Do you install Lithostitched?(1.20+)**
Yes
**Log**
Each log is a different, newly generated world and chunks
[crash-2024-07-06_19.46.14-server.txt](https://github.com/user-attachments/files/16167293/crash-2024-07-06_19.46.14-server.txt)
[crash-2024-07-09_07.36.23-server.txt](https://github.com/user-attachments/files/16167295/crash-2024-07-09_07.36.23-server.txt)
[crash-2024-07-10_12.26.26-server.txt](https://github.com/user-attachments/files/16167296/crash-2024-07-10_12.26.26-server.txt)

**Comment by ChoiceTheorem** [comment]
Remove all mr_ctov_ mods first, they aren't needed in CTOV for 1.20.1

**Comment by ChoiceTheorem** [comment]
The advice above should solve your problem, now may I ask you a favour?
Out of these compats you use:

- CTOV - Beautify Compat 2.0
- CTOV - Farmer Delight Compat 2.1
- CTOV - Gazebo compat 1.0
- CTOV - Paladins & Priests compat 1.0
- CTOV - Villagers Plus Compat 2.0
- CTOV - Wizards Compat 2.0a

Test them out which one is the culprit.

**Comment by ChoiceTheorem** [comment]
@ECrites Any update?

**Comment by ChoiceTheorem** [comment]
I performed a test. It's CTOV - Wizard Compat I'll delete that version from circulation
