### ISSUE TITLE
[BUG] Server Logs Reporting Non-Existent Template Pool Reference

### ISSUE THREAD

**Issue by Fyoncle** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#174]
**Describe the bug**
![image](https://github.com/user-attachments/assets/8edf0259-3957-435d-9185-637c34abddb4)

**To Reproduce**
Steps to reproduce the behaviour:
1. Use The Mod On A Server

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.5

**Do you install Lithostitched?(1.20+)**
Yes

**Log**
https://mclo.gs/jwOEEg4 No full log required, only this part is related to CTOV

**Comment by ChoiceTheorem** [comment]
Is this fresh install or updating? Those log artifact can be dismissed if it's updating

**Comment by Fyoncle** [comment]
> Is this fresh install or updating? Those log artifact can be dismissed if it's updating

Happened after a update.

**Comment by ChoiceTheorem** [comment]
I assure you it's not a problem at all.

**Comment by Fyoncle** [comment]
> I assure you it's not a problem at all.

Thanks ❤️
