### ISSUE TITLE
A way to decrease/modify spawn rates of CTOV villages

### ISSUE THREAD

**Issue by dadadadaan** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#178]
**Is your feature request related to a problem? Please describe.**
This isn't a problem, per say. More just quality of life.

**Describe the solution you'd like**
If CTOV could generate a config file similarly to other mods, that would probably be the most concise solution on the user end.

**Describe alternatives you've considered**
I've searched online for hours, though I may not be searching in the right places to be fair. I've checked Reddit, GitHub repos, and a bunch of Google searches over the past week.

**Additional context**
N/A

**Comment by ChoiceTheorem** [comment]
I may introduce configs for CTOV 1.21.

**Comment by dadadadaan** [comment]
Is there any way to modify the spawn rates using datapacks for 1.20?

**Comment by ChoiceTheorem** [comment]
Confer the minecraft wiki on how to adjust structure frequency

**Comment by dadadadaan** [comment]
Would it just be a matter of adjusting the spawn rate of vanilla villages and CTOV follows suit, or would I need to adjust the data specifically for CTOV's villages?

**Comment by ChoiceTheorem** [comment]
You can adjust vanilla village and CTOV will follow suit.

**Comment by MatiCugno69** [comment]
Hi, i've tried your suggestion and it didn't work in a flat world. Normal villages are affected but CTOV ones are not. I changed the settings through a datapack i made, it taps into "data/minecraft/worldgen/structure_set/villages.json", is this correct?

**Comment by ChoiceTheorem** [comment]
Read this wiki and this should solve your issues.
https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/wiki/Adjusting-village-frequency

**Comment by Molukke** [comment]
Hey, it seems you may have accidentally copy pasted the 1.20 link to the 1.21 entry in the wiki.
The 1.20 version is incompatible with 1.21.

**Comment by ChoiceTheorem** [comment]
I'll make 1.21 one later
