### ISSUE TITLE
[BUG] Village Smith loot table entry error

### ISSUE THREAD

**Issue by ImWhiff** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#183]
Old loot table uses "name" to use default smith village loot table making chests empty.
![smith](https://github.com/user-attachments/assets/95f55f08-c466-4058-9b22-7aff58075984)

Switching it to "value" fixed it.
![newsmith](https://github.com/user-attachments/assets/9c9685e5-efc0-4446-bc9c-320601653f72)

**Comment by ChoiceTheorem** [comment]
Fixed in the next version of CTOV 1.21.
