### ISSUE TITLE
[BUG] Some generation issues with windmills of "Create: Structures"

### ISSUE THREAD

**Issue by Josuburga** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#187]
**Describe the bug**
In some of the villages the windmills added by the Create: Structures are generated without walls. For example I found this issue in a mangrove swamp village and in a snowy one (I don't know the type of that one exactly because I found it while exploring, sorry)

**To Reproduce**
Steps to reproduce the behaviour:
1. Install CTOV and Create: Structures (there is in-built compatibility)
2. Go to a Mangrove Swamp Village or some other village to find this issue (it's just in some of them)

**Expected behaviour**
To all of these windmills to generate correctly, or that in those specific villages to not generate due to this bug

**Screenshots**
![2024-08-05_12 02 08](https://github.com/user-attachments/assets/5df8e184-1b8c-4e1d-b75f-964f1495391b)
![2024-08-05_12 06 33](https://github.com/user-attachments/assets/49cdda40-a77f-4821-86df-b963005d7765)

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.6

**Do you install Lithostitched?(1.20+)**
Yes

**Comment by ChoiceTheorem** [comment]
Some of them doesn't have walls. Screenshot some footage for me

**Comment by ChoiceTheorem** [comment]
- Those windmills are designed without walls, as weird as it is.
- Your concern about frequency is noted I think I'll limit them to 1-2 per village in the next update

**Comment by Josuburga** [comment]
> * Those windmills are designed without walls, as weird as it is.

Then wouldn't it be better to not have windmills in those villages? Because it's really strange to find those structures without walls at all. In the other villages they generate correctly, so it's not that they wouldn't generate anywhere, right?

**Comment by ChoiceTheorem** [comment]
I might revise the build to have walls if I have a way to keep them in line with the rest of the village.

**Comment by Josuburga** [comment]
Ok, and one last thing I want to know. This is completely sepparated from the bug I told here, just my curiosity. Is it normal that sometimes the villages are generated in really "vertical" places? (places like a big mountain for example). There are situations where some houses end up "floating", inside the mountain or in a cave that's just below the village, which is a little bit strange.

**Comment by ChoiceTheorem** [comment]
A normal but will try to avoid situation
