### ISSUE TITLE
[Forge 1.20.1] More Villagers houses consistently generate empty chests

### ISSUE THREAD

**Issue by polykatt** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#189]
Some of village structures from the More Villagers mod always have empty chests. This issue is with the forester and engineer villager houses. Often causing lag spikes/freezing when opening these chests. Not too sure if there are any other professions that have chests in their respective structures but the oceanographer and hunter chests are fine.

Latest version of CTOV 3.4.5

**Comment by ChoiceTheorem** [comment]
Send me a log!

**Comment by polykatt** [comment]
Oh, my bad Here it is.
[latest.log](https://github.com/user-attachments/files/16569855/latest.log)

**Comment by ChoiceTheorem** [comment]
Will investigate further!

**Comment by ChoiceTheorem** [comment]
Unable to replicate
