### ISSUE TITLE
[BUG] 1.19.2 Loot Table not exist

### ISSUE THREAD

**Issue by Skullians** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#193]
**Describe the bug**
We've only seen this issue in Taiga villages but may extend to others.
When opening chests in a Taiga village (archer rooms) with Lootr, we get `The loot table for this container [ctov:village/taiga/archer] resolved to empty and loot could not be generated. Check your 'latest.log' for errors.`

We are on the latest 1.19.2 version. 
How do we fix this?

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to taiga village on latest 1.19.2 Fabric version with Lootr.
2. Open a Archer room lootr chest
4. See the error

**Expected behaviour**
See loot

**Screenshots**
https://cdn.discordapp.com/attachments/1192096690413510686/1273276404385054740/image.png?ex=66be068f&is=66bcb50f&hm=21f5e503a5e969a382acd2497f72670458a503ebed7b8e3aab88a427b53b49ee&

**Minecraft Version**
1.19.2

**CTOV Version**
3.2.6c

**Add-ons used (Before 1.20)**

**Do you install Lithostitched?(1.20+)**
No - not on 1.20+

**Log**
https://mclo.gs/MJ8rm4I

**Additional context**
None

**Comment by ChoiceTheorem** [comment]
Issue is known in 1.19 but will not work on due to limited time

**Comment by Skullians** [comment]
> Issue is known in 1.19 but will not work on due to limited time

Was this solved in later versions? If so if you have the time could you link the commit that resolved it so I can take a look at it?

**Comment by Skullians** [comment]
Was this solved in later versions? If so if you have the time could you link the commit that resolved it so I can take a look at it?

**Comment by ChoiceTheorem** [comment]
It was several months ago I forgot which patch I fix it.
