### ISSUE TITLE
[BUG] Domestication Innovation Pet Shops have no Animals

### ISSUE THREAD

**Issue by SdeSpencer** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#194]
**Describe the bug**
Pet Shops (with Domestication Innovation) have no animals

**To Reproduce**
Steps to reproduce the behaviour:
1. Have both CTOV and Domestication Innovation installed
2. Go to any pet shop in a CTOV village
3. See there are no animals

**Expected behaviour**
There to be animals in the pet shop, lining up with pet shops as they exist in standard Domestication Innovation pet shops

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.5

**Do you install Lithostitched?(1.20+)**
Yes

**Log**
[latest.log](https://github.com/user-attachments/files/16642782/latest.log) (I doubt this will be useful, but for completeness)

**Comment by ChoiceTheorem** [comment]
I forgot to put a disclaimer that this will happen, anyway I'm try to replicate Alex's way of placing pets

**Comment by kirballs** [comment]
This problem still persists to me in version 3.4.7

**Comment by ChoiceTheorem** [comment]
Really? Does every village pet shop is empty? or only some?

**Comment by kirballs** [comment]
In one village with two pet shops i found one with a wolf and one empty, another village had both empty, and they were newly generated

**Comment by ChoiceTheorem** [comment]
So some spawn huh? Okay

**Comment by kirballs** [comment]
I found a large desert village with like 10 shops all empty...

**Comment by ChoiceTheorem** [comment]
It largely depends on where in the village it is located. A more central
location is more likely to have pets

**Comment by kirballs** [comment]
Aren't all pet shops supposed to have pets by definition?

**Comment by ChoiceTheorem** [comment]
What I said is the technical limitation of spawning pets in the shops.
Minecraft structure spawns by sizes.

**Comment by kirballs** [comment]
is this bug gonna be revised or are you keeping it like this, cause repurposed structures villages has no problems and even put alex mobs in shops

**Comment by ChoiceTheorem** [comment]
I may redo it a bit more
