### ISSUE TITLE
[Compat] Mushroom mods

### ISSUE THREAD

**Issue by 7OOTnegaTerces** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#195]
**What mod does your feature request relate to? Please briefly describe it.**

It's more than one, so I have a general solutions suggestion, but in particular:
Mod name: Mushroom Fields
Mod ID(optional):
CurseForge: https://www.curseforge.com/minecraft/mc-mods/mushroom-fields
Curseforge download(The higher it is, the higher the priority): 2,537

Mod name: Extended Mushrooms
Mod ID(optional):
CurseForge: https://www.curseforge.com/minecraft/mc-mods/extended-mushrooms
Curseforge download(The higher it is, the higher the priority): 6,092,953

**I read this repo's wiki page and issues that this mod isn't on the list of already compatible mod.**
- [X] Yes

**Describe the compatibility you'd like**
Mods like the above that add new terrain items (giant mushrooms in this case) should do so before this mod in world gen so that this mod overwrites their structures with the village structures.  This would not only look better, but it makes more sense for the villagers to chop down mushrooms (or whatever other mod's terrain feature) to build their village, than for the mushrooms to chop down the village.  Villages should always win against terrain, so this mod's world gen should happen as late in the world gen priority que as possible.

**Additional context**
I'm running NeoForge and am currently in Minecraft 1.20.1, and will be for the foreseeable future, so an update to that version would be much appreciated!!!  Thank you for this awesome mod!!!

**Comment by ChoiceTheorem** [comment]
I'll consider extended mushroom compat but likely to be delayed due to irl circumstances

**Comment by ChoiceTheorem** [comment]
Compatibility to do 
- Not terrain collision [Already is as of current patch]
- Glowshroom and Poisonshroom house variant. [To-do]

**Comment by 7OOTnegaTerces** [comment]
Sorry, I was slightly wrong here, there’s only a terrain collision issue with the Mushroom Fields mod, but those house ideas sound interesting!!!

**Comment by ChoiceTheorem** [comment]
Attempt implementing in 1.20.x. Not working due to a bug in lithostitched
