### ISSUE TITLE
[Compat] Another Furniture

### ISSUE THREAD

**Issue by federkey** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#197]
**What mod does your feature request relate to? Please briefly describe it.**
Mod name: Another Furniture
Mod ID(optional):
CurseForge: https://www.curseforge.com/minecraft/mc-mods/another-furniture
Modrinth: https://modrinth.com/mod/another-furniture
Curseforge download(The higher it is, the higher the priority): 18.893.922
**I read this repo's wiki page and issues that this mod isn't on the list of already compatible mod.**
- [V] Yes

**Describe the compatibility you'd like**
It would be cool for furniture from this mod to spawn in CTOV villages.

**Additional context**
I'm willing to the compat myself, if explained how to do so.

**Comment by ChoiceTheorem** [comment]
Too extensive to cover. I can't reasonably create compatibility with this mod without remaking CTOV from the ground up
