### ISSUE TITLE
No villagers spawn when changing the size to 1 or 2 via data pack

### ISSUE THREAD

**Issue by T3chDelicious** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#198]
Changing the value of "size" for the village type files found in "data -> ctov -> worldgen -> structure -> small, medium and/or large" to lower than 3 causes the game to not spawn villagers.

I love the style and architecture approach from CTOV but the sizes of the villages are way to big for my personal taste and I want stay more vanilla. The size of 2 is perfect for me but this causes to not spawn any villagers (guard villagers do spawn).

Am I missing something in my data pack?

**Comment by ChoiceTheorem** [comment]
You count any piece from the village center. 1 is for the starting road. 2
is for next house/road 3 is the minimum for villager spawning
