### ISSUE TITLE
Compat issue between Dynamic Trees and CTOV MC 1.18.2

### ISSUE THREAD

**Issue by Flugel3** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#2]
Hi, I'm posting this issue on the githubs for both mods... I've seen dynamic trees work well with some structure mods and not so well with others. basically here's the issue:
![2022-09-11_18 54 50](https://user-images.githubusercontent.com/78325529/189552559-6bbadd57-971e-46c5-a55b-d997d0b170ac.png)
![2022-09-11_18 54 46](https://user-images.githubusercontent.com/78325529/189552561-3458c299-c854-4e8b-913a-c17944b1a360.png)
![2022-09-11_18 54 33](https://user-images.githubusercontent.com/78325529/189552565-fc3e899e-5ebf-46ff-abc3-65caf3d38a74.png)

These are new chunks with both mods loaded in properly... This could just be a consequence both of the density of this particular forest... I'm unsure.

Regardless I'd say it's probably not a huge issue but can ruin the structures from CTOV if there are too many trees around. Overall a minor issue.

**Comment by ChoiceTheorem** [comment]
I deem it to be on Dynamic Trees ends.
