### ISSUE TITLE
Beautify Support

### ISSUE THREAD

**Issue by gigawhip** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#20]
[Beautify ](https://www.curseforge.com/minecraft/mc-mods/beautify-decorate)adds a [Botanist](https://github.com/Pandarix/Beautify/wiki/All-you-need-to-know#villagers) who focuses on flowers and [gardening-related items](https://github.com/Pandarix/Beautify/wiki/All-you-need-to-know#hanging-flowerpots). The mod has over 200k downloads.

![image](https://user-images.githubusercontent.com/103098495/222625552-6d065329-fd1b-4235-9edd-583c030dc266.png)

## Concerns

The Botanist thematically conflicts with More Villagers' Florist for which you already have a compat.

**Comment by ChoiceTheorem** [comment]
Up for consideration! Conflicts aren't that much of an issue!

**Comment by ChoiceTheorem** [comment]
Added in #26
