### ISSUE TITLE
[BUG] Waystones still spawning, even when village waystones generation is disabled.

### ISSUE THREAD

**Issue by OhDuffo** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#200]
**Describe the bug**
Waystones still generate in CTOV villages, even when waystone village generation is disabled in the Waystones config files.

**Minecraft Version**
1.20.1

**CTOV Version**
[Forge]CTOV-v3.4.5

**Did you install Lithostitched?(1.20+)**
Yes

**Additional Information**
I know this was an open issue before, but it was closed because someone had to make a custom datapack for this to work. Honestly, that doesn't seem like a solution. Not everyone knows how to make a datapack. Please add a config for CTOV village waystone generation.

**Comment by ChoiceTheorem** [comment]
Maybe I'll upload the solution from #153 as a downloadable modification pack.

**Comment by aviemet** [comment]
Sorry, is this addressed? I'm unable to prevent waystones from spawning in villages. The workarounds from the referenced issue don't work for me. I want to use CTOV, but I don't want waystones to generate in the overworld.

**Comment by ChoiceTheorem** [comment]
No way to turn that off for now
