### ISSUE TITLE
[Compat] Fabric Waystones Compatibility (Bug?)

### ISSUE THREAD

**Issue by mrburger** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#202]
Mod name: Fabric Waystones
Mod ID(optional): fwaystones
CurseForge: 
Modrinth: https://modrinth.com/mod/fwaystones/version/3.3.1+mc1.20.1

The mod claims support for Fabric Waystones. Using 1.20.1, CTOV 3.4.6, and Fabric Waystones 3.3.2, they won't generate naturally. I made a lithostitched compat port. All of Fabric 7 used as a base.

I saw waystones as a namespaced ID, but for some reason fwaystones is different like that.
[CTOV Fabric Waystones Litho.zip](https://github.com/user-attachments/files/16840150/CTOV.Fabric.Waystones.Litho.zip)

**Comment by ChoiceTheorem** [comment]
Good, I will add it to CTOV itself in the next update!

**Comment by ChoiceTheorem** [comment]
Already added to CTOV 3.4.9a! Incoming in 3.5.3b or 3.5.4.
