### ISSUE TITLE
[CRASH] swamp village crash

### ISSUE THREAD

**Issue by prismsplitter** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#205]
**Describe the bug**
In both singleplayer and multiplayer, coming within range of a newly generated swamp village, close enough for the initial villagers to spawn, crashes the game.

**To Reproduce**
Steps to reproduce the behaviour:
4. See the error

**Expected behaviour**
Swamp villagers spawn when a player is within range of a newly generated swamp village

**Screenshots**

**Minecraft Version**
1.20.1
**CTOV Version**
3.4.6 and 3.4.7

**Do you install Lithostitched?(1.20+)**
Yes
**Log**

**Additional context**
My suspicion is that the swamp villagers spawning in are causing the crash, because disabling the mod and going into the village spawns no villagers but prevents the crash.

**Comment by ChoiceTheorem** [comment]
Send me the crash log

**Comment by prismsplitter** [comment]
[crash-2024-09-01_17.46.57-server.txt](https://github.com/user-attachments/files/16956256/crash-2024-09-01_17.46.57-server.txt)

**Comment by ChoiceTheorem** [comment]
Remove all mr_ctov mods. They aren't needed.

**Comment by ChoiceTheorem** [comment]
BTW which modpack are you using?

**Comment by prismsplitter** [comment]
I'm using a custom modpack I made for me and one other player, so there could possibly be some incompatibilities somewhere.
Apologies for the delayed response!

**Comment by ChoiceTheorem** [comment]
You use bugged version of mr_ctov mods which isn't needed

**Comment by prismsplitter** [comment]
Assumed so, since removing them fixed the issue. Thank you!

**Comment by ChoiceTheorem** [comment]
I find it confusing why people still use the buggy version of the compat
that isn't needed.

**Comment by prismsplitter** [comment]
In my case, it's that the compatibility mods came up when looking at other mods, and that led me to your overhaul mod. I assumed the compatibility mods were needed, since there were ones for several mods I'm using. Dunno if this is why other people use them, but it's certainly at least one reason.
