### ISSUE TITLE
[Compat]Guard Villagers spawn control config

### ISSUE THREAD

**Issue by Yuri2187** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#208]
Mod name:Guard Villagers
Modrinth:https://modrinth.com/mod/guard-villagers
Curseforge download:42,813,402
**I read this repo's wiki page and issues that this mod isn't on the list of already compatible mod.**
- Yes

**Describe the compatibility you'd like**
Since CTOV(1.20.1 version 3.4.7 forge) is a mod generates massive village structures, it also generates a ton of guard villagers, this kills my fps in modpack, add a config or limit to this would be a improvement.
Here's a comparison of vanilla spawn and CTOV guardian villagers spawn
![2024-09-18_18 26 42](https://github.com/user-attachments/assets/3c466508-9f57-48c5-9596-73b7e46eaa2a)
![2024-09-18_18 12 27](https://github.com/user-attachments/assets/7518dc99-bdb7-4633-926c-abc93edb20c0)

**Comment by ChoiceTheorem** [comment]
CTOV villages will spawn exactly 6 guard villagers regardless of size.
