### ISSUE TITLE
[BUG]Jungle villages of all sizes can cause severe terrain damage

### ISSUE THREAD

**Issue by bubucao** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#209]
**Describe the bug**
Jungle villages of all sizes can cause severe terrain damage.

And although similar jungle tree villages do not destroy the terrain, floating trapdoors may appear. (perhaps jungle villages also have this small bug, but I haven't seen it)

**Screenshots**
Jungle village:
![2024-09-20_23 02 25](https://github.com/user-attachments/assets/b74ac7b1-95d8-4652-b00b-36ac2b6fa22e)
![2024-09-20_23 07 30](https://github.com/user-attachments/assets/6587dccb-d3e0-4936-83f5-c46cdb686fd3)
![2024-09-20_23 09 13](https://github.com/user-attachments/assets/1b07ae75-fee1-49dd-9602-fa1c2ca12d9c)
![2024-09-20_23 18 23](https://github.com/user-attachments/assets/90b1ebf2-0cd2-4314-8503-3bc5061d53b4)

jungle tree village:
![2024-09-20_23 11 59](https://github.com/user-attachments/assets/2a5ca0b3-7053-4563-81ee-bce412915d13)
![2024-09-20_23 20 20](https://github.com/user-attachments/assets/9248a7c6-0dce-4620-97e0-dd663626cd9b)

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.7

**Add-ons used**
No extra mods (only explorer's compass)

**Do you install Lithostitched?(1.20+)**
Yes

**Comment by ChoiceTheorem** [comment]
Hotfix incoming!
