### ISSUE TITLE
Chef's Delight Support

### ISSUE THREAD

**Issue by gigawhip** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#21]
[Chef's Delight](https://www.curseforge.com/minecraft/mc-mods/chefs-delight-fabric) simply adds Cook and Chef professions to Farmer's Delight, for which you already have a compat. The mod has over 200k downloads. It's only for Fabric today, but the Forge version is being pushed imminently.

![image](https://user-images.githubusercontent.com/103098495/222626540-4c9a802b-ed06-493e-9f88-0a60290832c3.png)

**Comment by ChoiceTheorem** [comment]
Up for consideration!

**Comment by gigawhip** [comment]
Done 🎉
