### ISSUE TITLE
Crash when loading chunks containing 'minecraft:red_cut_sandstone' from ctov:small/village_desert_oasis

### ISSUE THREAD

**Issue by FieryFlamingo13** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#212]
I am unable to load the chunks that contain 'minecraft:red_cut_sandstone' as it it considered an unknown block type

**Comment by Rewilon** [comment]
Bug is still alive.

[crash-2024-10-12_14.15.30-server.txt](https://github.com/user-attachments/files/17350058/crash-2024-10-12_14.15.30-server.txt)
