### ISSUE TITLE
Whenever i try entering a world or creation one this mod causes a crash. 

### ISSUE THREAD

**Issue by YugPatel2425** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#213]
Whenever I try entering the world or creating one this mod causes minecraft to crash. I have tried loading worlds without this and they load fine. I am attaching my crash log please help me solve the problem.

https://bytebin.lucko.me/QXPvWfdNjg

**Minecraft Version**
1.20.1

**CTOV Version**
3.4.9

**Add-ons used (Before 1.20)**
beautify, chefs-delight, vending machine, create structures, croptopia

**Comment by ChoiceTheorem** [comment]
Remove all add-ons

**Comment by YugPatel2425** [comment]
I already tried that but the issue still persists.

**Comment by ChoiceTheorem** [comment]
Remove all-ons, wait for an update and reset the chunk after an update

**Comment by YugPatel2425** [comment]
Still not working. It says loading world then a saving world screen appears immediately and then the game crashes.

**Comment by ChoiceTheorem** [comment]
Wait for an update that wasnt there yet when you retired. I'll deliver a quick fix

**Comment by ChoiceTheorem** [comment]
Fix uploaded

**Comment by Carsonated** [comment]
[latest.log](https://github.com/user-attachments/files/17180156/latest.log)
Looks like it's still happening with the newest patch on forge 1.20.1 (fresh world)
![image](https://github.com/user-attachments/assets/8881dc51-d651-4eac-a71e-c76bdfbd2b72)
