### ISSUE TITLE
Whenever I try entering the world or creating one this mod causes minecraft to crash

### ISSUE THREAD

**Issue by YugPatel2425** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#214]
Whenever I try entering the world or creating one this mod causes minecraft to crash. I have tried loading worlds without this and they load fine. I am attaching my crash log please help me solve the problem.

https://bytebin.lucko.me/QXPvWfdNjg

Minecraft Version
1.20.1

CTOV Version
3.4.9

Add-ons used (Before 1.20)
beautify, chefs-delight, vending machine, create structures, croptopia

**Comment by ChoiceTheorem** [comment]
Duplicate with #213
