### ISSUE TITLE
[CRASH] Game crashes or soft locks upon visiting villages

### ISSUE THREAD

**Issue by Carsonated** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#215]
**Describe the bug**
Teleporting to certain villages causes the game to either soft lock or crash. The latest log calls "Caused by: com.mojang.brigadier.exceptions.CommandSyntaxException: Unknown block type 'minecraft:red_cut_sandstone' at position 0: <--[HERE]"

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a world with this seed: -1767586584221345168
2. Locate the nearest desert village biome
3. Teleport to said village
4. The game will do two of the mentioned above

**Expected behaviour**
Normal generation behavior, no crashing

**Screenshots**
The video showcases what happens when the mod is uninstall (the first clip) and when it is installed (second clip). Both tests on newly generated worlds on the same seed.
https://github.com/user-attachments/assets/dbe4947b-2e41-4e99-af5f-50195c3bad0f

**Minecraft Version**
1.20.1
**CTOV Version**
3.4.9
**Add-ons used (Before 1.20)**

**Do you install Lithostitched?(1.20+)**
Yes (1.3.1a)
**Log**
[latest.log](https://github.com/user-attachments/files/17119456/latest.log)

**Comment by ChoiceTheorem** [comment]
Is the same as #213
