### ISSUE TITLE
[BUG] Errors during world creation

### ISSUE THREAD

**Issue by massacring** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#218]
**Describe the bug**
When creating a new world, 3 errors are logged in the game output window. The 3 errors are:
- Couldn't load tag ctov:wares/cardboard_box as it is missing following references: wares:cardboard_box (from [Forge]CTOV-3.4.9b.jar)
- Couldn't load tag ctov:wares/sealed_delivery_agreement as it is missing following references: wares:sealed_delivery_agreement (from [Forge]CTOV-3.4.9b.jar)
- Couldn't parse element loot_tables:ctov:chests/village/village_forager
  com.google.gson.JsonSyntaxException: Missing expand, expected to find a Boolean

**To Reproduce**
Steps to reproduce the behaviour:
1. Start the game
2. Click on 'Singleplayer'
3. Click on 'Create New World'
4. See the error

**Expected behaviour**
I would expect there to be no errors, when all I'm doing is going through the UI. The world isn't even being created yet.

**Minecraft Version** 1.20.1

**CTOV Version** 3.4.9b

**Do you install Lithostitched?(1.20+)**
Yes, version 1.3.1a

**Log**
[latest.log](https://github.com/user-attachments/files/17256075/latest.log)

**Comment by ChoiceTheorem** [comment]
A benign bug, will not be fixed
