### ISSUE TITLE
Buzzier Bees Support

### ISSUE THREAD

**Issue by gigawhip** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#22]
Abnormals' [Buzzier Bees](https://www.curseforge.com/minecraft/mc-mods/buzzier-bees) adds and [Apiarist](https://minecraftabnormals.fandom.com/wiki/Buzzier_Bees#Apiarist_Villagers) (beekeeper) villager. The mod has over 10mil downloads. However it seems to be Forge only with no plans to expand to Fabric.

![image](https://user-images.githubusercontent.com/103098495/222627169-24831620-d682-4ac8-bc87-4d4458962b82.png)

**Comment by ChoiceTheorem** [comment]
Not applicable in any CTOV version.

**Comment by gigawhip** [comment]
Sounds good. So that I can avoid making undesirable feature requests in the future, could you let me know what made this mod "invalid" and "not applicable"? Is it perhaps the lack of Fabric support?

**Comment by ChoiceTheorem** [comment]
This feature uses "Apiarist villager" and "Honey Pot" which are removed in 1.18 according to the devs. CTOV is 1.18.2+ mod. In a nutshell, suggests a mod that generates structures in villages that is 1.18.2+. Preferably 1.19+

**Comment by gigawhip** [comment]
> removed in 1.18 according to the devs

I had no idea. Thank you!
