### ISSUE TITLE
[BUG] Crash when loading chunks containing 'minecraft:red_cut_sandstone' from ctov:small/village_desert_oasis

### ISSUE THREAD

**Issue by Rewilon** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#220]
Bug [#212](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/issues/212) seems to still be alive on my server.

I'm using CTOV 3.4.9b on 1.20.1(Forge) with several other mods.

[crash-2024-10-12_14.15.30-server.txt](https://github.com/user-attachments/files/17350108/crash-2024-10-12_14.15.30-server.txt)

**Comment by ChoiceTheorem** [comment]
1. Remove all CTOV add-on
2. Reset that chunk and try again

**Comment by ChoiceTheorem** [comment]
Yes, the culprit is identified as CTOV-Wares add-ons
