### ISSUE TITLE
Namespace changes for BYG

### ISSUE THREAD

**Issue by ModernGamingWorld** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#223]
**Describe the bug**

Its's because your using BYG when the mod ID is biomeswevegone for 1.20.1 forge

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to '\data\ctov\loot_tables\chests\village\village_forager.json' 
2. Click on 'village_forager.json'
3. Scroll down to 'to where it shows BYG and notice the ID is wrong.'
4. See the error

**Expected behaviour**

**Screenshots**

**Minecraft Version**
1.20.1

**CTOV Version**
Latest

**Add-ons used (Before 1.20)**

**Do you install Lithostitched?(1.20+)**
Yes/No(You install it first)
**Log**

**Additional context**

**Comment by ChoiceTheorem** [comment]
Note that the log error will be there even if I act according to your suggestion and you don't have BYG/BWG

**Comment by Fyoncle** [comment]
> Note that the log error will be there even if I act according to your suggestion and you don't have BYG/BWG

Maybe make it so it checks if the mod is installed?

**Comment by ChoiceTheorem** [comment]
I can do that for 1.21.
