### ISSUE TITLE
[CRASH] Mod or conflict with mod causes game to crash on world creation screen

### ISSUE THREAD

**Issue by munchimunchies** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#229]
**Describe the bug**
After several minutes of turning off mods and opening and closing the game repeatedly, this is the mod that is causing the game to crash when I try to get to the create a world screen. The crash report insists that the cause of the crash is a mod called "FPS reducer", but when I turned off the overhauled village mod and left everything else on including the FPS reducer mod, the game didn't crash.

**Minecraft Version**
Forge 1.20.1

**CTOV Version**
3.4.10

**Do you install Lithostitched?(1.20+)**
Yes

**Log**
https://pastebin.com/qmue7Qxy

**Comment by ChoiceTheorem** [comment]
Possibly not related to CTOV.
