### ISSUE TITLE
Config for fabric

### ISSUE THREAD

**Issue by eatenpancreas** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#232]
Hi, I'm not sure if this intentional, but on fabric there is no config file anywhere present as far as i can tell. It would be nice to have an option to reduce spawn rates for villages, for balancing purposes for a modpack. If i'm missing some way to edit this, let me know.

**Describe the solution you'd like**
A config file with spawn rates for villages

**Comment by ChoiceTheorem** [comment]
Not going to be available for a while! Check out the wiki for a stopgap!
