### ISSUE TITLE
ChoiceTheorem's Overhauled Village + Big Globe

### ISSUE THREAD

**Issue by Rubinchik11095** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#234]
Hello, I ran into a problem that ChoiceTheorem's Overhauled Village mod cannot create its buildings in the world of Big Globe. 
I would like you to support Big Globe with your mod

**Comment by ChoiceTheorem** [comment]
Issue noted, though I think we can fix this by fixing this issue in Big globe. https://github.com/Builderb0y/BigGlobe/issues/53

**Comment by ChoiceTheorem** [comment]
Check out BuilderBoy discord server for the compact!
