### ISSUE TITLE
Friends & Foes integrations in Snowy Village variant use sandstone

### ISSUE THREAD

**Issue by gigawhip** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#24]
This seems unintentional. If it matters, this was encountered with Terralith.

![2023-03-12_00 17 03](https://user-images.githubusercontent.com/103098495/224532835-480bb7c4-8aa0-4403-bbbb-04d51da921e5.png)
![2023-03-12_00 17 15](https://user-images.githubusercontent.com/103098495/224532840-003077bd-6fea-4944-8caf-d5cf3db6468d.png)

**Comment by ChoiceTheorem** [comment]
Yes, it is a mistake on my end! I'll fix it soon!

**Comment by ChoiceTheorem** [comment]
Fixed on some commit earlier
