### ISSUE TITLE
Immersive Engineering Compat?

### ISSUE THREAD

**Issue by starskyC** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#25]
## What is wrong?
Many villages don't have their workstation from IE. I could only find them in vanilla villages. Currently I'm also using repurposed structure & the compat pack it provided for IE. I really love the structures this mod provides so please let me know if there is any workaround.
## What version of minecraft do you use?
1.18.2
## What version of CTOV do you use?
2.9.2

**Comment by ChoiceTheorem** [comment]
Mod integrations are currently not available for any version of 1.18.2 Update to enjoy mod integrations!
