### ISSUE TITLE
Server crash due to typo

### ISSUE THREAD

**Issue by sauramel** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#28]
[crash-2023-03-13_09.50.16-server.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/10962912/crash-2023-03-13_09.50.16-server.txt)

See crash report, appears to be an error caused by this typo 'minecraft:smooth_sanstone_stairs'
When generating the  ctov:medium/village_desert structure.
pls fix

**Comment by ChoiceTheorem** [comment]
As a temporary measure removed friends and foes add-on for now for your server.

**Comment by ChoiceTheorem** [comment]
You can update this datapack now to version 1.1. ctov-friends-and-foes-add-on-v1-0.zip
