### ISSUE TITLE
Failed to load datapacks

### ISSUE THREAD

**Issue by TheButterbrotMan** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#3]
https://bytebin.lucko.me/4VOsHiwHGV

**Comment by ChoiceTheorem** [comment]
CTOV version, Fabric version and minecraft version please?

**Comment by ChoiceTheorem** [comment]
Looks like you are using fabric for 1.19 on 1.18.2

**Comment by TheButterbrotMan** [comment]
Ops sorry, its Minecraft 1.18.2 with Fabric 0.14.9 in a new world.

**Comment by ChoiceTheorem** [comment]
Can't replicate the problem. Latest CTOV doesn't have this issue.
