### ISSUE TITLE
Crash when I try to use the command locate, and no village is generated [1.19.2]

### ISSUE THREAD

**Issue by projdevops23** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#31]
I installed this mod after generate my world in vanilla but since it's been installed, It seems like the vanilla villages don't generate correctly on 1.19.2, since the mod is installed there is no village that is generated at all.

Additionally, using the command to locate villages (vanilla village and ctov village) make my game / server crashes.

Here crash log of the locate command use on my server : 
[crash-2023-03-25_16.00.32-server.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/11069363/crash-2023-03-25_16.00.32-server.txt)

**Comment by ChoiceTheorem** [comment]
AFAIK, villages generate fine at a greater distance. I strongly discourage locating ctov village individually, instead locating a tag of villages is always a wiser option and note that it will incur lags even on high-end servers. Your crash comes from a lag from /locate
