### ISSUE TITLE
Crash in Mod Options

### ISSUE THREAD

**Issue by bcrotty** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#32]
What is wrong?
![image](https://user-images.githubusercontent.com/6155964/228346429-a5faabbe-90cf-426f-8c73-ecb6bed39910.png)
When I click on the mod in the main menu mods list or from mod options in-game, Minecraft crashes to the the desktop.
What version of minecraft do you use?
1.19.2 (All the Mods 8)
What version of CTOV do you use?
3.1.8
The log or screen capture of the bug
https://pastebin.com/Ac268CYm

**Comment by macks2008** [comment]
I think I managed to fix it on my fork of the repository. I plan to open a PR (my second PR ever, so bear with me) shortly to discuss the changes.

**Comment by ChoiceTheorem** [comment]
I'll deal with it next release!

**Comment by macks2008** [comment]
Sounds good. Honestly the PR may not happen as I am fighting with github's new(-ish) authentication workflow. I can try to get it in if you want, though the two commits I made are pretty simple either way (one copies the logo and updates the reference, the other deletes the old one). Tested the fix against Java 17 with IntelliJ IDEA just to be sure.
