### ISSUE TITLE
server logs errors

### ISSUE THREAD

**Issue by LeDucDuQ** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#36]
Hello! i just find out that my server logs look orange and red lines so i talk about this to a devlopper from the modpack and then he tell me to upload my server's log to fix error

logs : https://mclo.gs/XDOtK1V

**Comment by ChoiceTheorem** [comment]
Doesn't seem to be related to my mod. Read red lines and visit the dev of each mod in red.
