### ISSUE TITLE
Block minecraft:smooth_sandstone_stairs does not have property 'facin' at position 34

### ISSUE THREAD

**Issue by purejosh** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#37]
**Describe the bug**
Server crashing when generating chunk.

**To Reproduce**
Install CTOV mod, load certain chunk with smooth sandstone stairs, crash. 

**Minecraft Version**
Fabric 1.19.2 Server

**CTOV Version**
v3.2.1

**Log**
https://gist.github.com/purejosh/17638c87245a5ca13b800ae59251215c

**Additional context**
I've searched every single NBT file and every .json in this .jar file, and I cannot for the life of me find a misspelling of "facin" anywhere. Could be my search tools, but I've tried real hard to find this one for you.

**Comment by fzzyhmstrs** [comment]
I have found the (or a) source of this bug in my integration with the desert_oasis village. My crystal workshop has the misspelling noted above until fixed in the patch going out soon today.

**Comment by ChoiceTheorem** [comment]
Do you use any add-on? It might be the add-on. I'll check it later.

**Comment by fzzyhmstrs** [comment]
I haven't tested fully yet, but I think this is resolved with my latest updates. I had a typo in my own integration with CTOV

**Comment by ChoiceTheorem** [comment]
Which mod are you developing? I can add you to my list.

**Comment by fzzyhmstrs** [comment]
Amethyst Imbuement. I have my own library for injecting structures into villages. Seems like I made a typo on one
