### ISSUE TITLE
Fails to load datapack

### ISSUE THREAD

**Issue by TheButterbrotMan** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#4]
Modversion: [Universal]CTOV-v2-9-2.jar
Fabricversion: 0.19.4
Minecraftversion: 1.18.2

latest.log: https://bytebin.lucko.me/wQXnaElqIu

**Comment by ChoiceTheorem** [comment]
Can't replicate

**Comment by TheButterbrotMan** [comment]
Anything you changed from v2.9 to v2.9.2 maybe? 2.9 is working for me without problems

**Comment by TheButterbrotMan** [comment]
i can try 2.9.1 if this helps you

**Comment by ChoiceTheorem** [comment]
Updating causes the crash. Fall back or make a new world.

**Comment by TheButterbrotMan** [comment]
> Updating causes the crash. Fall back or make a new world.

That also happens to me when i make a new world

**Comment by ChoiceTheorem** [comment]
log?

**Comment by ChoiceTheorem** [comment]
Unable to replicate. Will investigate with more cases.

**Comment by TheButterbrotMan** [comment]
> log?

https://bytebin.lucko.me/PDGvLDXfgd
