### ISSUE TITLE
Smith/Librarian chests empty.

### ISSUE THREAD

**Issue by BishopBone** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#43]
**Describe the bug**
Some profession chests are completely empty. This includes the librarian smith house are completely empty while others like the leatherworker and shepherd are mostly empty. Regular houses and the cleric seems to be normal.
**To Reproduce**
Steps to reproduce the behaviour:
Download 3.2.1 and find a village with these proffessions. 

**Expected behaviour**
I expected there to be items in the chests. The same world had items in the chests with the previous version on ctov.

**Screenshots**

**Minecraft Version**
1.19.2
**CTOV Version**
3.2.1
**Log**
No error log.

**Additional context**

**Comment by ChoiceTheorem** [comment]
Duplicate with #38
