### ISSUE TITLE
Crash CTOV 3.2.1 

### ISSUE THREAD

**Issue by therealpro101** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#44]
Im currently running a Modpack that is using CTOV on Minecraft 1.19.2. Im running a server and this is my crash report https://pastebin.com/JwxVqTit

**Comment by ChoiceTheorem** [comment]
Are you updating your mod?

**Comment by therealpro101** [comment]
I updated it and it fixed it, sorry just wanted to close this for you forgot about this.
