### ISSUE TITLE
large villages extremely lag the game and crash whenever you try to locate them

### ISSUE THREAD

**Issue by FullMetalMaster** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#45]
**Describe the bug**
large villages extremely lag the game and crash whenever you try to locate them

**To Reproduce**
Steps to reproduce the behaviour:
1.18.2 FORGE load the mod and find a large village 

**Expected behaviour**
MASSIVE frame drops

**Screenshots**

**Minecraft Version** 1.18.2

**CTOV Version**
[Universal]CTOV-v2.9.4
**Log**

**Additional context**
would be greatly appreciated if either mobs in this area were turned down or this area was greatly optimized

**Comment by ChoiceTheorem** [comment]
Due to rarity, lags are common and should be expected.
