### ISSUE TITLE
[Suggestion] Dusty decorations

### ISSUE THREAD

**Issue by moninformateur** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#46]
**Suggestion**
[Dusty Decorations](https://www.curseforge.com/minecraft/mc-mods/dusty-decorations) introduces a few simple decorations to the game. It could greatly enhances the decorations used in the towns, notably for the vendor stands.

**Comment by ChoiceTheorem** [comment]
Thanks for suggestion but I might not use the block in my mod.
