### ISSUE TITLE
Questager Support

### ISSUE THREAD

**Issue by dehen** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#5]
Is it possible to add [Questagers](https://www.curseforge.com/minecraft/mc-mods/questagers) support? It'd be great if they could spawn in the villages like More Villagers do. I was digging around myself, trying to figure it out, but I'm not datapack-brained enough to solve the issue.

**Comment by ChoiceTheorem** [comment]
I'll work on it.

**Comment by ChoiceTheorem** [comment]
Will not add compat until the mod is rewritten
