### ISSUE TITLE
Crashes on start on 1.19.4

### ISSUE THREAD

**Issue by TheaRTGGaming** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#51]
I Loaded the version of your mod compatible for 1.19.4 and well 
it says "Mod ctov requires minecraft 1.19 or above, and below 1.19.4
Currently, minecraft is 1.19.4" now idk what happen there, but that can't be right.

**Comment by ChoiceTheorem** [comment]
Version and platform?

**Comment by TheaRTGGaming** [comment]
Mod Version: {V3.2.3?} Download from Cruseforge, and I downloaded it for Forge Windows 10

The mod was fix in V:3.2.4b and the message did not show up. so Fixed I guess?

**Comment by ChoiceTheorem** [comment]
Yes, I was fixing some consistency within the code and created more bugs in the process. Now 3.2.4b should fix it.
