### ISSUE TITLE
[1.19.3] Idea: Fabric Waystones compatability

### ISSUE THREAD

**Issue by HoneyBadger1337** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#56]
I know you've got a [fabric waystone](https://www.curseforge.com/minecraft/mc-mods/waystones-fabric) mod compatible already but I was wondering if we could get the same for [Fabric Waystones][(https://www.curseforge.com/minecraft/mc-mods/fabric-waystones) as well :)

**Comment by ChoiceTheorem** [comment]
It takes just a config edit. I should have that in the description already.

**Comment by endigma** [comment]
This doesn't work I don't think

**Comment by ChoiceTheorem** [comment]
> This doesn't work I don't think

Make a separate issue with the format in mind, thank you!
