### ISSUE TITLE
Villages don't have houses.

### ISSUE THREAD

**Issue by Orgamorsh** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#59]
What is wrong?
Villages spawn without houses.

What version of minecraft do you use?
1.19.2

What version of CTOV do you use?
3.2.5

The log says "Empty or non-existent pool: minecraft:village/{Biome}/houses" for every biome.
[latest.log](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/12169070/latest.log)

**Comment by ChoiceTheorem** [comment]
Definitely not CTOV bug, do you have any other village mods on your set?

**Comment by Orgamorsh** [comment]
I have Mca reborn and vamparism.

**Comment by ChoiceTheorem** [comment]
You should consult with Vampirism for that.

**Comment by ChoiceTheorem** [comment]
No info given closing this issue
