### ISSUE TITLE
Wizards compat using minecraft:deepslate_stairs, causing a crash

### ISSUE THREAD

**Issue by Dangosaurus** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#60]
What is wrong?
Wizards compat uses `minecraft:deepslate_stairs` instead of `deepslate_brick_stairs` which causes a crash due to `minecraft:deepslate_stairs` being an unknown block type when the tower feature generates.

What version of minecraft do you use?
1.19.2

What version of CTOV do you use?
3.2.5

The log or screen capture of the bug
[crash-2023-07-28_00.32.04-server.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/12190575/crash-2023-07-28_00.32.04-server.txt)

**Comment by ChoiceTheorem** [comment]
Quick fix is on the way! This issue will be closed after this issue is resolved.

**Comment by WesselvanGils** [comment]
I believe this bug got reintroduced in 1.20.1. 

MC version: 1.20.1
CTOV version: 3.3.5b

[crash.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/12907828/crash-2023-10-14_21.15.23-server.txt)
