### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Developer2704** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#63]
The ctovvillages are amazing but the vanilla villages often intersect with Ctov villages or just look off and are less complex or helpful so can you add a config to disable vanilla villages?

**Comment by ChoiceTheorem** [comment]
Join the discord server and go to #faq and config

**Comment by Developer2704** [comment]
what about people that do not have a discord account? can you add an faq and feature request template to github

**Comment by ChoiceTheorem** [comment]
1. I'll post a download link on the faq on both CF and MR later on.
2. Sure thing, man!
