### ISSUE TITLE
Loot Table bug

### ISSUE THREAD

**Issue by zonosaki** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#64]
**What is wrong?**
Unable to fill loot chest in ResourceKey[minecraft:dimension / minecraft:overworld] at class_2338{x=-641, y=70, z=-491} as the loot table 'ctov:village/plains/farm' couldn't be resolved! Please search the loot table in `latest.log` to see if there are errors in loading.

**What version of minecraft do you use?**
AOF6 1.9.1 *(1.19.2)*

**What version of CTOV do you use?**
3.2.5

[latest.log](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/12346249/latest.log)

**Comment by ChoiceTheorem** [comment]
A valid bug but I might not fix it unless there's one in 1.20. My ability to support is limited to the latest version of minecraft.
