### ISSUE TITLE
[ISS datapack] Lootr chests in some houses roll for wrong loot table

### ISSUE THREAD

**Issue by moninformateur** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#65]
**Describe the bug**
When opening a chest in a house with a Iron Spells and Spellbooks (ISS) contaning an inscription table (the houses with the copper rods), the loot table rolled is the one from the fabric "Wizard" mod

**To Reproduce**
Steps to reproduce the behaviour:
1. Load CTOV, Lootr and the ISS datapack.
2. Visit houses with Inscription tables (generally the houses with the copper lightning rod)
3. Open the chest on the 1st story.
4. A wizards:chests/village_wizard loot_table is rolled.

**Expected behaviour**
The rolled loot table should be a loot table from Iron's Spells and Spellbooks.

**Minecraft Version**
Forge 1.20.1-47.1.3
**CTOV Version**
3.3.3

**Log**
```
Unable to fill loot chest in ResourceKey[minecraft:dimension / minecraft:overworld] at 
BlockPos{x=259, y=148, z=2652} as the loot table 'wizards:chests/village_wizard' couldn't 
be resolved! Please search the loot table in `latest.log` to see if there are errors in loading.
```

**Comment by ChoiceTheorem** [comment]
Will address that in August CTOV patch

**Comment by moninformateur** [comment]
Thanks!

**Comment by ChoiceTheorem** [comment]
Uploaded patch to modrinth! Curseforge is waiting for approval.
