### ISSUE TITLE
Villages not being overhauled at all.

### ISSUE THREAD

**Issue by deadtoxaris** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#66]
**Describe the bug**
Villages arent overhauled. At all, further info below.
We saw that CTOV got compatibility with certain new mods we use and we wanted to update CTOV, but then villages arent overhauling Vanilla ones even in new worlds.
We used to have CTOV-Fabric-Forge-3-0-1 and it worked amazing, no Vanilla villages anywhere in world.

**To Reproduce**
_Steps to reproduce the behaviour:_
1. Download [Universal]CTOV-v3.1.3 (this is for 1.19.2, i also tried with newest one [[Universal]CTOV-v3.2.5] which contains 1.19.2 compatibility )
2. Start minecraft (Fabric loader 0.14.22 - 1.19.2)
3. Load singleplayer
4. Villages arent overhauled :/
(i am not sure if i need to do anything else except download mod and put it in .minecraft -> mods folder, but for older CTOV version it worked like that)

**Expected behavior**
CTOV villages overhauling Vanilla ones.

**Screenshots**
new CTOV:
![village Vanilla](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/112664272/b67e6a0e-dda1-4523-9a90-bc4668d44fbf)
![village Vanilla close](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/112664272/60f4638e-cdf0-4daa-b417-9848d711414c)
older CTOV:
![village CTOV](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/112664272/482d5d17-1ba4-42e6-b0c2-1a79e4969409)

**Minecraft Version**
1.19.2 Fabric loader 0.14.22
**CTOV Version**
[Universal]CTOV-v3.1.3
**Log**
no log
**Additional context**
no additional problem

**Comment by deadtoxaris** [comment]
![image](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/112664272/9aaba543-3641-4e29-9bf4-55d5f319a836)
i posted issue above without getting the context of this overview, i was reading it and i am confused with it cuz i dont know does that mean Vanilla villages will STILL be in world or not.. we use CTOV since last year and its strange to see Vanilla villages.. is there possibility to make all the villages overhauled in newer version ?

**Comment by ChoiceTheorem** [comment]
Installing a "config" datapack from the discord server.
