### ISSUE TITLE
CTOV Farmer Delight farm's spawn without water

### ISSUE THREAD

**Issue by KirboSoftware** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#67]
**Describe the bug**
Like the title says

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a village large village of CTOV
2. Find a farm with Farmer Delight crops
3. See there is no water

**Expected behaviour**
That the farm has water

**Screenshots**
![2023-08-24_12 08 08](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/80041873/fdca1780-5ae0-4243-b9fc-d380538771cd)
![image](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/80041873/e7500541-c337-4893-8aaa-28925840aafb)

**Minecraft Version**
1.20.1
**CTOV Version**
3.3.3

**Log**

**Additional context**

**Comment by ChoiceTheorem** [comment]
Will investigate and fix in September update.

**Comment by ChoiceTheorem** [comment]
Problem is also found in 1.19.x need more time to fix.

**Comment by ChoiceTheorem** [comment]
I get the reasons now. It's do to changes from F&F ends. Fixing within 1 week.

**Comment by ChoiceTheorem** [comment]
Uploading the fix to CF and Modrinth.
