### ISSUE TITLE
Messy structure spawning

### ISSUE THREAD

**Issue by Tomatobird8** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#7]
Seems like elevation changes mid village cause another structure to spawn very close to one another. Especially with small structures, the village can get very cluttered and chaotic. A large amount of villages seem to have this issue but especially savanna villages are prone to this for their small sctructure sizes. The fishing docks spawn can spawn all over the place + spawn floating water.

Solutions for fixing is I could think of is to expand the size of each structure (vanilla minecraft seems to include a bunch of ground below houses in the structure), or change structure spawning logic.

![image](https://user-images.githubusercontent.com/60841151/202638232-d69c07e2-3dc4-427e-a7b0-e51257dbb51d.png)
![image](https://user-images.githubusercontent.com/60841151/202638169-fef5626b-ba92-44ac-a21d-3f6406b85015.png)
![image](https://user-images.githubusercontent.com/60841151/202638174-8fe3d9bc-4be7-4dcd-8025-dc7d4bcbcd92.png)
![image](https://user-images.githubusercontent.com/60841151/202638180-d09aefdb-1d30-4da8-83ae-2d40177a0f32.png)
![image](https://user-images.githubusercontent.com/60841151/202638182-d2d09731-8431-4b9c-adbc-64960b27070d.png)
![image](https://user-images.githubusercontent.com/60841151/202638189-dd7b2cd0-c93c-4820-970b-053013521268.png)
![image](https://user-images.githubusercontent.com/60841151/202638199-8bf81fc0-1cac-49f9-9fa4-44444e895c1b.png)

**Comment by ChoiceTheorem** [comment]
Exactly will happen in the far future updates.

**Comment by M0dEx** [comment]
Having the same issue on v2.9.2 (Minecraft 1.18.2)

![2023-03-21_22 46 47](https://user-images.githubusercontent.com/18428519/226749402-e9643b8c-d87d-410b-9694-38247bcbd755.png)
![2023-03-21_22 47 03](https://user-images.githubusercontent.com/18428519/226749412-deca856d-7f74-4555-a802-596e2e8a8003.png)

**Comment by ChoiceTheorem** [comment]
Will be eliminated by the coming reworks so this issue is closed.
