### ISSUE TITLE
server crash on different villages

### ISSUE THREAD

**Issue by mindryder** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#70]
**Describe the bug**
server crash on different villages chunk generate

**To Reproduce**
Steps to reproduce the behaviour:
4. See the error

**Minecraft Version** 1.20.1

**CTOV Version** 3.3.4

**Log**
[crash-2023-08-31_04.34.50-server.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/12484260/crash-2023-08-31_04.34.50-server.txt)

**Comment by mindryder** [comment]
[crash-2023-08-31_11.55.18-server.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/12484467/crash-2023-08-31_11.55.18-server.txt)

**Comment by Excalimbinhu** [comment]
Had the same issue here, tried with both Mod and DataPack. Mine crashed on medium/village_swamp generation

Minecraft Version 1.19.2
CTOV Mod Version: 3.2.5
CTOV DataPack Version: 3.2.3

CTOV Mod Crash Report:
[crash-2023-08-31_21.11.45-server.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/12491771/crash-2023-08-31_21.11.45-server.txt)

CTOV DataPack Crash Report:
[crash-2023-08-31_21.25.28-server.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/12491769/crash-2023-08-31_21.25.28-server.txt)

**Comment by ChoiceTheorem** [comment]
Try removing all add-on mods and readding them one by one it should helps me figure out where the problem is.

**Comment by Excalimbinhu** [comment]
I just tested these add-ons:
CTOV Beautify add-on
CTOV Chef's add-on
CTOV Paladins & Priests compat
CTOV Gazebo compat

And then I had the crash when I enabled CTOV Wizards compat

**Comment by ChoiceTheorem** [comment]
Redownload CTOV Wizards compat
