### ISSUE TITLE
Villagers stuck in japanese variant

### ISSUE THREAD

**Issue by Thari0** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#71]
**Describe the bug**
In japanese variant the windows are made of open trapdoors. 
Villagers try to exit houses through them and just stand inside next to the trapdoors.

**Expected behaviour**
For more natural feel, it should be changed to something that wont obstruct the villigers. 
Otherwise the village seems abounded.

**Minecraft Version**
1.19.2

**CTOV Version**
3.2.5

**Comment by ChoiceTheorem** [comment]
Due to aesthetic choice, I won't change it.
