### ISSUE TITLE
Unknown block type 'minecraft:deepslate_bricks_stairs' in ctov:medium/village_swamp

### ISSUE THREAD

**Issue by gardenappl** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#73]
I have a few addons installed and I'm not sure which one might've caused this. I also have LazyDFU installed (not sure if that's relevant)

[crash.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/12541357/crash.txt)

**Comment by ChoiceTheorem** [comment]
Note for myself:
This user uses following add-on: 
CTOV - Farmer Delight 
CTOV - Paragliders (Ruled out)
CTOV - Advanced Peripheral 
CTOV - PneumaticCraft: Repressurized

**Comment by ChoiceTheorem** [comment]
Redownload CTOV-Irons compat on modrinth!
