### ISSUE TITLE
[Suggestion] Datapack mods

### ISSUE THREAD

**Issue by ZEROX7** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#74]
mods i would like to get datapack addons
[Lightmans Currency](https://www.curseforge.com/minecraft/mc-mods/lightmans-currency)
[Create structers](https://www.curseforge.com/minecraft/mc-mods/create-structures)
[Floralis](https://www.curseforge.com/minecraft/mc-mods/floralis)

**Comment by ChoiceTheorem** [comment]
Added to #39 !
