### ISSUE TITLE
Fabric Waystones do not spawn in CTOV villages

### ISSUE THREAD

**Issue by endigma** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#75]
**Describe the bug**
Fabric Waystones do not spawn in CTOV villages.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 1.20.1 w/ CTOV
2. Visit village
3. No waystone

**Expected behaviour**
A waystone from Fabric Waystones to spawn

**Minecraft Version**
1.20.1-fabric

**CTOV Version**
ctov-3.3.4

**Add-ons used**
ctov-farmers-delight

**Comment by ChoiceTheorem** [comment]
Did you try editing the config first?

**Comment by endigma** [comment]
What config? There's no documentation and no config file I can see

**Comment by ChoiceTheorem** [comment]
Sorry for not being clear. I meant fabric waystone config not CTOV config.

**Comment by endigma** [comment]
Ok, you mean adding all the CTOV villages into `add_waystone_structure_piece`?

**Comment by ChoiceTheorem** [comment]
I made a GitHub gist [here](https://gist.github.com/ChoiceTheorem/3875c53cac91812b6ba937a9561bf37a)

**Comment by SettingDust** [comment]
Updated config https://github.com/LordDeatHunter/FabricWaystones/issues/218#issuecomment-1803378981

**Comment by ChoiceTheorem** [comment]
Underground village is intentionally left as an empty shell for further development.
