### ISSUE TITLE
Server constantly times out and freezes when loading new chunks

### ISSUE THREAD

**Issue by Meekpression** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#76]
**Describe the bug**
World Gen fails to keep up with player on server, which causes server lag., resulting in a timeout server state in which it won't crash, but will wait on world statistics to update.

**To Reproduce**
Generate new chunks

[16Sep2023 08:37:11.445] [Worker-Main-51/WARN] [ModernFix/]: The namespace ctov contains an outdated structure file, which can cause worldgen lag. Please view debug.log for the full filename, determine which mod provides the structure, and report to the mod/datapack author, including the debug log.

**Expected behaviour**
Server not timing out and crashing due to this issue with generating structures 

**Screenshots**

**Minecraft Version** 
1.20.1 

**CTOV Version** 
3.3.4

**Add-ons used**
All The Mods 9

**Log**
[debug (1).log](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/12641044/debug.1.log)
[latest.log](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/12641045/latest.log)

**Additional context**
This issue was happening on a few modpack versions, but it has escalated and is very frequent now since we updated to the latest. The mod version is the same however. I'm wondering if its one of those cases where it'll start to happen once a x amount already has been generated.

**Comment by ChoiceTheorem** [comment]
- All the mods 9 has a lot of worldgen mods in it. Have you try disable CTOV before?
- From debug log reading the problem seems to not be on CTOV.
- Try disable half the mod until you find the culprit mod.
