### ISSUE TITLE
Reduce the number of villages

### ISSUE THREAD

**Issue by Donokami** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#77]
Hey!
Thank you for the great mod, the villages looks beautiful.
Howewer, while playing in real situation we felt like we had almost a village every 200 blocks. It would be great to have an option (in a mod config file setting or something like this) to add more space in the placement of each villages. Like this, we could choose an easier way to play the game, or harden the gameplay by making these cools looking houses more rare!

**Comment by ChoiceTheorem** [comment]
There is an active bug regarding that. Try reinstall the mod after September Update!

**Comment by ChoiceTheorem** [comment]
Update to 3.3.5a or 3.2.6b depends on your minecraft version.
