### ISSUE TITLE
[1.18.2] [Forge] Villagers not spawning 

### ISSUE THREAD

**Issue by Optify1** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#8]
With no other mods installed only a few villagers spawn in every village 
![2022-11-27_15 44 36](https://user-images.githubusercontent.com/118838704/204160548-2f1c8db3-d175-4284-8067-fa7c8d18f7f8.png)
![2022-11-27_15 29 50](https://user-images.githubusercontent.com/118838704/204160553-0ae8645a-6674-4897-b8be-0f15670eda0e.png)
![2022-11-27_16 04 30](https://user-images.githubusercontent.com/118838704/204160604-0265095e-408e-47d2-8076-407713bee1e0.png)

**Comment by DeshiDesu** [comment]
I'm getting the same problem
