### ISSUE TITLE
Asset error

### ISSUE THREAD

**Issue by Willem07** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#80]
village names don't work ctov-3.3.4.jar\assets\ctov\lang

For example, with the Corail Adventurer mod, I want to create a map to search for a village, but there is no *Beach Village(Large)* in the name of the map, instead writes *large/village_beach*

**Comment by ChoiceTheorem** [comment]
I investigate further and found that the dev doesn't use assets to make UI display. Nothing can be done from my end unless I unnecessarily rehauled my mod.
