### ISSUE TITLE
[BUG] Serverside crash on startup

### ISSUE THREAD

**Issue by ChromaPIE** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#82]
**Describe the bug**
Don't know if it's actually caused by the latest update of CTOV but im still submitting it here

**Minecraft Version** 1.20.1 Fabric

**CTOV Version**
3.3.5

**Add-ons used**
Beautify compat
F&F compat

**Log**
https://mclo.gs/qMOUsHp (only the related part)

**Comment by ChoiceTheorem** [comment]
Update to 3.3.5a
