### ISSUE TITLE
[BUG] Crash on clicking the "create new world" button.

### ISSUE THREAD

**Issue by RubenRME** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#83]
**Describe the bug**
Crash on clicking the "create new world" button. Crash log doesn't indicate CTOV as the culprit but one by one testing shows it comes from here.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on singleplayer
2. Click on Create New World
3. Observe

**Expected behaviour**
The world creation screen is shows

**Minecraft Version**
1.20.1

**CTOV Version**
3.3.5

**Log**
[crash-2023-09-30_00.47.43-client.txt](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/12772622/crash-2023-09-30_00.47.43-client.txt)

**Comment by ChoiceTheorem** [comment]
Bug acknowledged, CTOV 3.2.6/3.3.5 has no backward compatibility at the moment. Fixing
