### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kkyr456tw** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#84]
Describe the bug:
/locate structure ctov: does not work

To Reproduce:
Steps to reproduce the behaviour:

1.Click on singleplayer
2.Click on Create New World
3.Execute /locate structure ctov:medium/village_beach

Expected behaviour:
Normal execution /locate structure ctov:

Minecraft Version:1.20.1

fabricVersion:0.14.22

CTOV Version:3.3.5a

TerralithVersion:v2.4.6

![123](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/89146700/f040323d-01f5-4bdc-b813-6e0925bac6e2)

**Comment by ChoiceTheorem** [comment]
Update terralith to 2.4.7!
