### ISSUE TITLE
[BUG] villages not spawning/unable to locate villages 1.19.2

### ISSUE THREAD

**Issue by puppygruel** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#86]
Locate structure command not working, not sure if villages are spawning and not being located or simply aren't spawning as I haven't found any, but I could have been unlucky

**To Reproduce**
Steps to reproduce the behaviour:
1. Create new world
2. Use /locate structure command

**Screenshots**

![image](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/110639086/692e3961-a7bf-4a57-9895-0d8a13929cd8)

**Minecraft Version**
1.19.2

**CTOV Version**
3.2.6b

I noticed a similar issue was reported for 1.20, however the fix listed being update terralith doesn't apply as terralith is updated to the highest version available, and the version suggested in fix does not exist for 1.19.2. **This also occurs with terralith not installed.**

**Comment by ChoiceTheorem** [comment]
It's separate issue entirely I'll fix it ASAP

**Comment by ChoiceTheorem** [comment]
Should be fixed
