### ISSUE TITLE
[BUG] Incorrect loot tables referenced in structure chests in Farmer's Delight add-on

### ISSUE THREAD

**Issue by nitrofenix** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#87]
**Describe the bug**
Loot tables of Farmer's Delight jobsite structure chests for the following village types are incorrect:
```
beach
christmas
desert
desert_oasis
halloween
jungle_tree
mesa
mesa_fortified
mountain
mushroom
plains
savanna
snowy_igloo
swamp_fortified
taiga
taiga_fortified
```

**To Reproduce**
Steps to reproduce the behaviour:
1. `/locate` a CTOV village for one of the above biome types.
2. Look for a Farmer's Delight farm.
3. Open the chest, see the following error (block data included for context):
![image](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/50662839/e7a3664f-46da-4c6b-a44a-a4ad047da197)

**Expected behaviour**
Loot table should be `ctov:village/common/farm`, loot should be generated as expected:
![image](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/50662839/616602e8-1d12-4761-bfbd-d413f44ad8c3)
![image](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/assets/50662839/89bb497a-b156-432b-bf9e-8a57d47518dc)

**Minecraft Version**
1.20.1

**CTOV Version**
3.3.4

**Add-ons used**
ctov-farmers-delight-add-on-v2-0.zip

**Additional context**
The affected structure chests have been fixed in the attached zip, as previously [posted in Discord](https://discord.com/channels/894248275841003542/1140476430774452344/1160115628947030047), however I've not attempted to fix any other issues with these structures (i.e., such as missing water, etc): [ctov-farmers-delight-add-on-v2-0a.zip](https://github.com/ChoiceTheorem/ChoiceTheorem-s-overhauled-village/files/12844076/ctov-farmers-delight-add-on-v2-0a.zip)

**Comment by ChoiceTheorem** [comment]
Problem Identified. Will fixed in October update!

**Comment by ChoiceTheorem** [comment]
Upload the fixed version

**Comment by drakray** [comment]
I got the same problem on Fabric 1.21
