### ISSUE TITLE
OV -IE compat: no Immersive Engineering house

### ISSUE THREAD

**Issue by Ashendale** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#88]
**Describe the bug**
Cannot find the IE house anywhere, using compat mod version 2.0

**To Reproduce**
1- create a world with IE, Terralith, CTOV, CTOV IE compat, Explorer's Compass (to make it easy to find and teleport to places), Village Nullifier (vanilla villages).
2 - go anywhere: plains, desert, savanna, swamp...
3 - repeat 10+ times and call it quits

**Expected behaviour**
I didn't expect to find them everywhere. I'm still half expectant that you say I was just unlucky, but finding none anywhere frustrated me.

**Minecraft Version**
1.20.1
**CTOV Version**
3.3.5a
**Add-ons used**
CTOV - Immersive Engineering compat 2.0 (mod version)

**Additional context**
Since (at least looking at curse/modrinth) IE only came out for 1.20.1 on Oct 5th, and the compat mod exists since June 22nd, I'm guessing there may be some issue somewhere... I have no evidence that the issue is on this side, but I had to start somewhere, and the discrepancy of dates for the mod releases struck me as weird.

**Comment by ChoiceTheorem** [comment]
Ok, I will investigate and try to fix within this month.

**Comment by ChoiceTheorem** [comment]
It does spawn IE tents at a very low rate.
