### ISSUE TITLE
Please add Compatibility with Mod Better Archeology

### ISSUE THREAD

**Issue by Zamanos** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#89]
Good Day I would love it if you could add a compatibility patch for the mod Better Archeology ver. 1.20.1 on curseforge:  https://www.curseforge.com/minecraft/mc-mods/better-archeology    This mod adds a new villager entity the archeologist with a archeology table, and it would be perfect to be included with your mod!   Thank you so much for your consideration and time, and this great mod!

**Comment by ChoiceTheorem** [comment]
Transfer to Compatibility discussion
