### ISSUE TITLE
Compatibility for Minecraft Comes Alive Reborn 

### ISSUE THREAD

**Issue by welcometodainternet** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#90]
MCA Reborn is a mod that makes villagers interactable.

Currently the supported game versions are 1.18.2 to 1.20.1

Please make a compatibility mod for the 1.20.1 version.

[Link](https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn) (Curseforge)
[Link](https://modrinth.com/mod/minecraft-comes-alive-reborn) (Modrinth)

**Comment by ChoiceTheorem** [comment]
Compatible as is.
