### ISSUE TITLE
[BUG] Mod File ctov-3.3.5b.jar needs language provider javafml:46 or above to load

### ISSUE THREAD

**Issue by Omnimetatron** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#92]
**Describe the bug**
The mod is not compatible with Neoforged for 1.20.2

**To Reproduce**
Steps to reproduce the behaviour:
1. Try to load the mod using Neoforged for 1.20.2

**Expected behaviour**
Minecraft makes it to the main menu.

**Screenshots**

**Minecraft Version**
1.20.2
**CTOV Version**
3.3.5b
**Add-ons used**

**Log**
https://gist.github.com/Omnimetatron/8d23991e1ee9dc3afd8777091b8e22ca

**Additional context**
Neoforged became a "hard" fork from Forge since MC 1.20.2

**Comment by ChoiceTheorem** [comment]
I will publish Neoforge CTOV ASAP.

**Comment by ChoiceTheorem** [comment]
The neoforge version should be up within 3 hours!
