### ISSUE TITLE
[BUG] Gazebo Spawn Limit Doesn't Work As Expected

### ISSUE THREAD

**Issue by Moozipan** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#93]
**Describe the bug**
Using CTOV with the Gazebo mod and Gazebo compat often generates more than 1 gazebo per village (up to 4), regardless of the original limit of 1. Do you think it's possible to limit the spawn rate on your end?

**Minecraft Version**
Fabric 1.20.1

**CTOV Version**
3.3.6

**Comment by ChoiceTheorem** [comment]
Not as of now
