### ISSUE TITLE
[BUG] Underground villages not in datapack 1.19.2 Forge

### ISSUE THREAD

**Issue by RichPrune** [ChoiceTheorem/ChoiceTheorem-s-overhauled-village#94]
**Describe the bug**
ooks like the ctov underground villages are excluded from the worldgen for some reason. but the "Merchantiere Extroadinare" quest requires it.

adding 
{
    "structure": "ctov:large/village_underground",
    "weight": 1
},
{
    "structure": "ctov:medium/village_underground",
    "weight": 4
},
{
    "structure": "ctov:small/village_underground",
    "weight": 15
},

to the data/minecraft/worldgen/structure_set/village.json
inside the 
config\paxi\datapacks/ctov-3-2-3edited.zip 
seems to fix it

**Minecraft Version**
1.19.2
**CTOV Version**
3.2.3

**Add-ons used**

**Log**

**Additional context**

**Comment by ChoiceTheorem** [comment]
Underground village is an unused content. Consult with the quest mod for further fix.
